-- MobileInfoAnalytics database schema v1
-- Target: PostgreSQL 15+ as provided by Supabase.
--
-- The six source schemas preserve the table layout requested in
-- database_layout.txt.  The warehouse schema adds two things that the source
-- layout cannot safely represent on its own: the immutable raw payload and an
-- append-only price history.  This keeps re-scrapes useful for historical BI
-- while the source tables continue to represent the latest known state.

begin;

create schema if not exists original;
create schema if not exists daraz;
create schema if not exists mymobile;
create schema if not exists mega;
create schema if not exists whatamobile;
create schema if not exists whatmobile;
create schema if not exists warehouse;
create schema if not exists etl_private;
create schema if not exists api;

comment on schema original is
    'Canonical GSMArena product specification records.';
comment on schema warehouse is
    'Immutable landing records, historical prices, and cross-source views.';
comment on schema etl_private is
    'Internal helpers used by the versioned ingestion functions.';
comment on schema api is
    'Explicit Supabase RPC surface for ingestion, matching, and analytics.';

-- -------------------------------------------------------------------------
-- Canonical GSMArena tables
-- -------------------------------------------------------------------------

create table if not exists original.central_info (
    serial_number bigint generated by default as identity primary key,
    data_snapshot timestamptz not null default clock_timestamp(),
    name text not null,
    url text not null,
    network_id bigint generated by default as identity not null unique,
    launch_id bigint generated by default as identity not null unique,
    body_id bigint generated by default as identity not null unique,
    display_id bigint generated by default as identity not null unique,
    platform_id bigint generated by default as identity not null unique,
    memory_id bigint generated by default as identity not null unique,
    camera_back_id bigint generated by default as identity not null unique,
    camera_front_id bigint generated by default as identity not null unique,
    sound_loudspeaker text,
    sound_cable_jack boolean not null default true,
    features_id bigint generated by default as identity not null unique,
    battery_id bigint generated by default as identity not null unique,
    colors text[] not null default '{}'::text[],
    weight text not null default 'Weight Unknown',
    price numeric(14,2)[] not null
        default array[-1.00]::numeric(14,2)[],
    constraint original_central_name_uq unique (name),
    constraint original_central_url_uq unique (url),
    constraint original_central_name_present_ck
        check (btrim(name) <> ''),
    constraint original_central_url_http_ck
        check (url ~* '^https?://'),
    constraint original_central_price_present_ck
        check (cardinality(price) >= 1),
    constraint original_central_price_no_nulls_ck
        check (array_position(price, null) is null),
    constraint original_central_colors_no_nulls_ck
        check (array_position(colors, null) is null)
);

create table if not exists original.network (
    network_id bigint primary key
        references original.central_info (network_id) on delete cascade,
    "2g" boolean not null default true,
    "3g" boolean not null default true,
    "4g" boolean not null default false,
    "5g" boolean not null default true
);

create table if not exists original.launch (
    launch_id bigint primary key
        references original.central_info (launch_id) on delete cascade,
    announced text,
    status text
);

create table if not exists original.body (
    body_id bigint primary key
        references original.central_info (body_id) on delete cascade,
    dimensions text,
    weight text,
    build text,
    sim text,
    protection text
);

create table if not exists original.display (
    display_id bigint primary key
        references original.central_info (display_id) on delete cascade,
    type text,
    size text,
    resolution text,
    protection text
);

create table if not exists original.platform (
    platform_id bigint primary key
        references original.central_info (platform_id) on delete cascade,
    os text,
    chipset text,
    cpu text,
    gpu text
);

create table if not exists original.memory (
    memory_id bigint primary key
        references original.central_info (memory_id) on delete cascade,
    card_slot text,
    technology text,
    types text[] not null default '{}'::text[],
    constraint original_memory_types_no_nulls_ck
        check (array_position(types, null) is null)
);

create table if not exists original.camera_back (
    camera_back_id bigint primary key
        references original.central_info (camera_back_id) on delete cascade,
    specifications text[] not null default '{}'::text[],
    features text,
    video text[] not null default '{}'::text[],
    constraint original_camera_back_specs_no_nulls_ck
        check (array_position(specifications, null) is null),
    constraint original_camera_back_video_no_nulls_ck
        check (array_position(video, null) is null)
);

create table if not exists original.camera_front (
    camera_front_id bigint primary key
        references original.central_info (camera_front_id) on delete cascade,
    specifications text[] not null default '{}'::text[],
    features text,
    video text[] not null default '{}'::text[],
    constraint original_camera_front_specs_no_nulls_ck
        check (array_position(specifications, null) is null),
    constraint original_camera_front_video_no_nulls_ck
        check (array_position(video, null) is null)
);

create table if not exists original.features (
    features_id bigint primary key
        references original.central_info (features_id) on delete cascade,
    wlan text,
    bluetooth text,
    positioning text,
    nfc boolean not null default false,
    infrared_port boolean not null default false,
    radio boolean not null default true,
    usb text,
    back_finger_print boolean not null default false,
    side_finger_print boolean not null default false,
    in_display_finger_print boolean not null default false,
    sensors text
);

create table if not exists original.battery (
    battery_id bigint primary key
        references original.central_info (battery_id) on delete cascade,
    capacity text,
    wireless_charging boolean not null default false,
    charging text[] not null default '{}'::text[],
    constraint original_battery_charging_no_nulls_ck
        check (array_position(charging, null) is null)
);

create index if not exists original_central_snapshot_idx
    on original.central_info (data_snapshot desc);
create index if not exists original_central_name_lower_idx
    on original.central_info (lower(name));
create index if not exists original_central_price_gin_idx
    on original.central_info using gin (price);

-- -------------------------------------------------------------------------
-- Marketplace/source schemas.  All five have the same shape.  A listing is
-- first stored in secondary_info; central_info is its optional-to-create but
-- strict-when-present link to a canonical original product.  This permits
-- ingestion before product matching without weakening the requested NOT NULL
-- product_id rule.
-- -------------------------------------------------------------------------

do $schema$
declare
    source_schema text;
begin
    foreach source_schema in array
        array['daraz', 'mymobile', 'mega', 'whatamobile', 'whatmobile']
    loop
        execute format($ddl$
            create table if not exists %1$I.secondary_info (
                serial_number bigint generated by default as identity primary key,
                data_snapshot timestamptz not null default clock_timestamp(),
                name text not null,
                url text not null,
                network_id bigint generated by default as identity not null unique,
                launch_id bigint generated by default as identity not null unique,
                body_id bigint generated by default as identity not null unique,
                display_id bigint generated by default as identity not null unique,
                platform_id bigint generated by default as identity not null unique,
                memory_id bigint generated by default as identity not null unique,
                camera_back_id bigint generated by default as identity not null unique,
                camera_front_id bigint generated by default as identity not null unique,
                sound_loudspeaker text,
                sound_cable_jack boolean not null default true,
                features_id bigint generated by default as identity not null unique,
                battery_id bigint generated by default as identity not null unique,
                colors text[] not null default '{}'::text[],
                weight text not null default 'Weight Unknown',
                price numeric(14,2)[] not null
                    default array[-1.00]::numeric(14,2)[],
                constraint secondary_info_url_uq unique (url),
                constraint secondary_info_name_present_ck check (btrim(name) <> ''),
                constraint secondary_info_url_http_ck check (url ~* '^https?://'),
                constraint secondary_info_price_present_ck check (cardinality(price) >= 1),
                constraint secondary_info_price_no_nulls_ck
                    check (array_position(price, null) is null),
                constraint secondary_info_colors_no_nulls_ck
                    check (array_position(colors, null) is null)
            )
        $ddl$, source_schema);

        execute format($ddl$
            create table if not exists %1$I.central_info (
                serial_number bigint primary key
                    references %1$I.secondary_info (serial_number) on delete cascade,
                product_id bigint not null
                    references original.central_info (serial_number) on delete restrict,
                instance_number integer not null,
                constraint central_info_instance_positive_ck
                    check (instance_number > 0),
                constraint central_info_product_instance_uq
                    unique (product_id, instance_number)
            )
        $ddl$, source_schema);

        execute format($ddl$
            create table if not exists %1$I.network (
                network_id bigint primary key
                    references %1$I.secondary_info (network_id) on delete cascade,
                "2g" boolean not null default true,
                "3g" boolean not null default true,
                "4g" boolean not null default false,
                "5g" boolean not null default true
            )
        $ddl$, source_schema);

        execute format($ddl$
            create table if not exists %1$I.launch (
                launch_id bigint primary key
                    references %1$I.secondary_info (launch_id) on delete cascade,
                announced text,
                status text
            )
        $ddl$, source_schema);

        execute format($ddl$
            create table if not exists %1$I.body (
                body_id bigint primary key
                    references %1$I.secondary_info (body_id) on delete cascade,
                dimensions text,
                weight text,
                build text,
                sim text,
                protection text
            )
        $ddl$, source_schema);

        execute format($ddl$
            create table if not exists %1$I.display (
                display_id bigint primary key
                    references %1$I.secondary_info (display_id) on delete cascade,
                type text,
                size text,
                resolution text,
                protection text
            )
        $ddl$, source_schema);

        execute format($ddl$
            create table if not exists %1$I.platform (
                platform_id bigint primary key
                    references %1$I.secondary_info (platform_id) on delete cascade,
                os text,
                chipset text,
                cpu text,
                gpu text
            )
        $ddl$, source_schema);

        execute format($ddl$
            create table if not exists %1$I.memory (
                memory_id bigint primary key
                    references %1$I.secondary_info (memory_id) on delete cascade,
                card_slot text,
                technology text,
                types text[] not null default '{}'::text[],
                constraint memory_types_no_nulls_ck
                    check (array_position(types, null) is null)
            )
        $ddl$, source_schema);

        execute format($ddl$
            create table if not exists %1$I.camera_back (
                camera_back_id bigint primary key
                    references %1$I.secondary_info (camera_back_id) on delete cascade,
                specifications text[] not null default '{}'::text[],
                features text,
                video text[] not null default '{}'::text[],
                constraint camera_back_specs_no_nulls_ck
                    check (array_position(specifications, null) is null),
                constraint camera_back_video_no_nulls_ck
                    check (array_position(video, null) is null)
            )
        $ddl$, source_schema);

        execute format($ddl$
            create table if not exists %1$I.camera_front (
                camera_front_id bigint primary key
                    references %1$I.secondary_info (camera_front_id) on delete cascade,
                specifications text[] not null default '{}'::text[],
                features text,
                video text[] not null default '{}'::text[],
                constraint camera_front_specs_no_nulls_ck
                    check (array_position(specifications, null) is null),
                constraint camera_front_video_no_nulls_ck
                    check (array_position(video, null) is null)
            )
        $ddl$, source_schema);

        execute format($ddl$
            create table if not exists %1$I.features (
                features_id bigint primary key
                    references %1$I.secondary_info (features_id) on delete cascade,
                wlan text,
                bluetooth text,
                positioning text,
                nfc boolean not null default false,
                infrared_port boolean not null default false,
                radio boolean not null default true,
                usb text,
                back_finger_print boolean not null default false,
                side_finger_print boolean not null default false,
                in_display_finger_print boolean not null default false,
                sensors text
            )
        $ddl$, source_schema);

        execute format($ddl$
            create table if not exists %1$I.battery (
                battery_id bigint primary key
                    references %1$I.secondary_info (battery_id) on delete cascade,
                capacity text,
                wireless_charging boolean not null default false,
                charging text[] not null default '{}'::text[],
                constraint battery_charging_no_nulls_ck
                    check (array_position(charging, null) is null)
            )
        $ddl$, source_schema);

        execute format(
            'create index if not exists %I on %I.secondary_info (data_snapshot desc)',
            source_schema || '_secondary_snapshot_idx', source_schema
        );
        execute format(
            'create index if not exists %I on %I.secondary_info (lower(name))',
            source_schema || '_secondary_name_lower_idx', source_schema
        );
        execute format(
            'create index if not exists %I on %I.central_info (product_id)',
            source_schema || '_central_product_idx', source_schema
        );
        execute format(
            'create index if not exists %I on %I.secondary_info using gin (price)',
            source_schema || '_secondary_price_gin_idx', source_schema
        );
    end loop;
end
$schema$;

-- -------------------------------------------------------------------------
-- Immutable landing/history layer
-- -------------------------------------------------------------------------

create table if not exists warehouse.ingest_runs (
    run_id bigint generated by default as identity primary key,
    loader_name text not null default 'filestorage/csvToDataBase.py',
    target_kind text not null default 'supabase',
    source_manifest text,
    started_at timestamptz not null default clock_timestamp(),
    finished_at timestamptz,
    rows_attempted bigint not null default 0,
    rows_succeeded bigint not null default 0,
    rows_failed bigint not null default 0,
    status text not null default 'running',
    details jsonb not null default '{}'::jsonb,
    constraint ingest_runs_status_ck
        check (status in ('running', 'completed', 'completed_with_errors', 'failed')),
    constraint ingest_runs_counts_ck
        check (
            rows_attempted >= 0
            and rows_succeeded >= 0
            and rows_failed >= 0
        )
);

create table if not exists warehouse.raw_ingest (
    raw_id bigint generated by default as identity primary key,
    source_schema text not null,
    source_url text not null,
    source_file text,
    data_snapshot timestamptz not null,
    payload jsonb not null,
    payload_md5 text generated always as (md5(payload::text)) stored,
    ingested_at timestamptz not null default clock_timestamp(),
    constraint raw_ingest_source_schema_ck check (
        source_schema in (
            'original', 'daraz', 'mymobile', 'mega',
            'whatamobile', 'whatmobile'
        )
    ),
    constraint raw_ingest_url_http_ck check (source_url ~* '^https?://'),
    constraint raw_ingest_payload_object_ck
        check (jsonb_typeof(payload) = 'object'),
    constraint raw_ingest_event_uq
        unique (source_schema, source_url, data_snapshot, payload_md5)
);

create table if not exists warehouse.price_history (
    price_history_id bigint generated by default as identity primary key,
    source_schema text not null,
    source_serial_number bigint not null,
    product_id bigint
        references original.central_info (serial_number) on delete set null,
    source_url text not null,
    product_name text not null,
    data_snapshot timestamptz not null,
    price_position smallint not null,
    amount numeric(14,2) not null,
    currency_code text,
    ingested_at timestamptz not null default clock_timestamp(),
    constraint price_history_source_schema_ck check (
        source_schema in (
            'original', 'daraz', 'mymobile', 'mega',
            'whatamobile', 'whatmobile'
        )
    ),
    constraint price_history_position_ck check (price_position > 0),
    constraint price_history_amount_ck check (amount > 0),
    constraint price_history_currency_ck check (
        currency_code is null or currency_code ~ '^[A-Z]{3}$'
    ),
    constraint price_history_event_uq unique (
        source_schema, source_url, data_snapshot, price_position
    )
);

create table if not exists warehouse.etl_rejects (
    reject_id bigint generated by default as identity primary key,
    run_id bigint references warehouse.ingest_runs (run_id) on delete set null,
    source_schema text,
    source_file text,
    source_url text,
    rejected_at timestamptz not null default clock_timestamp(),
    error_code text not null,
    error_message text not null,
    payload jsonb
);

create index if not exists raw_ingest_source_snapshot_idx
    on warehouse.raw_ingest (source_schema, data_snapshot desc);
create index if not exists raw_ingest_url_idx
    on warehouse.raw_ingest (source_url);
create index if not exists raw_ingest_payload_gin_idx
    on warehouse.raw_ingest using gin (payload jsonb_path_ops);
create index if not exists price_history_product_time_idx
    on warehouse.price_history (product_id, data_snapshot desc);
create index if not exists price_history_source_time_idx
    on warehouse.price_history (source_schema, data_snapshot desc);
create index if not exists price_history_url_time_idx
    on warehouse.price_history (source_url, data_snapshot desc);
create index if not exists etl_rejects_run_idx
    on warehouse.etl_rejects (run_id, rejected_at desc);

-- Every listing, including records that have not yet been matched to a
-- canonical GSMArena product.  Price arrays retain their original order.
create or replace view warehouse.current_listings as
select
    'original'::text as source_schema,
    c.serial_number as source_serial_number,
    c.serial_number as product_id,
    1::integer as instance_number,
    c.data_snapshot,
    c.name,
    c.url,
    c.price
from original.central_info as c
union all
select 'daraz', s.serial_number, c.product_id, c.instance_number,
       s.data_snapshot, s.name, s.url, s.price
from daraz.secondary_info as s
left join daraz.central_info as c using (serial_number)
union all
select 'mymobile', s.serial_number, c.product_id, c.instance_number,
       s.data_snapshot, s.name, s.url, s.price
from mymobile.secondary_info as s
left join mymobile.central_info as c using (serial_number)
union all
select 'mega', s.serial_number, c.product_id, c.instance_number,
       s.data_snapshot, s.name, s.url, s.price
from mega.secondary_info as s
left join mega.central_info as c using (serial_number)
union all
select 'whatamobile', s.serial_number, c.product_id, c.instance_number,
       s.data_snapshot, s.name, s.url, s.price
from whatamobile.secondary_info as s
left join whatamobile.central_info as c using (serial_number)
union all
select 'whatmobile', s.serial_number, c.product_id, c.instance_number,
       s.data_snapshot, s.name, s.url, s.price
from whatmobile.secondary_info as s
left join whatmobile.central_info as c using (serial_number);

create or replace view warehouse.current_prices as
select
    listing.source_schema,
    listing.source_serial_number,
    listing.product_id,
    listing.instance_number,
    listing.data_snapshot,
    listing.name,
    listing.url,
    price.price_position,
    price.amount,
    case
        when listing.source_schema = 'original' then null
        else 'PKR'
    end as currency_code
from warehouse.current_listings as listing
cross join lateral unnest(listing.price) with ordinality
    as price(amount, price_position)
where price.amount > 0;

comment on column warehouse.current_prices.currency_code is
    'Marketplace prices are PKR. GSMArena Price[] positions can contain multiple currencies, so original rows intentionally remain NULL rather than being mislabeled.';

-- Custom schemas are private by default.  The functions file grants only the
-- narrow RPC functions to Supabase service_role; no browser role receives
-- direct table access.
do $security$
declare
    object_schema text;
    role_name text;
begin
    foreach object_schema in array array[
        'original', 'daraz', 'mymobile', 'mega',
        'whatamobile', 'whatmobile', 'warehouse', 'etl_private', 'api'
    ]
    loop
        execute format('revoke all on schema %I from public', object_schema);
        execute format('revoke all on all tables in schema %I from public', object_schema);
        execute format('revoke all on all sequences in schema %I from public', object_schema);
        execute format(
            'alter default privileges in schema %I revoke all on tables from public',
            object_schema
        );
        execute format(
            'alter default privileges in schema %I revoke all on sequences from public',
            object_schema
        );
        execute format(
            'alter default privileges in schema %I revoke execute on functions from public',
            object_schema
        );

        foreach role_name in array array['anon', 'authenticated']
        loop
            if exists (select 1 from pg_roles where rolname = role_name) then
                execute format(
                    'revoke all on schema %I from %I', object_schema, role_name
                );
                execute format(
                    'revoke all on all tables in schema %I from %I',
                    object_schema, role_name
                );
                execute format(
                    'revoke all on all sequences in schema %I from %I',
                    object_schema, role_name
                );
            end if;
        end loop;
    end loop;

    foreach object_schema in array array[
        'original', 'daraz', 'mymobile', 'mega',
        'whatamobile', 'whatmobile'
    ]
    loop
        execute format('alter table %I.central_info enable row level security', object_schema);
        if object_schema <> 'original' then
            execute format('alter table %I.secondary_info enable row level security', object_schema);
        end if;
        execute format('alter table %I.network enable row level security', object_schema);
        execute format('alter table %I.launch enable row level security', object_schema);
        execute format('alter table %I.body enable row level security', object_schema);
        execute format('alter table %I.display enable row level security', object_schema);
        execute format('alter table %I.platform enable row level security', object_schema);
        execute format('alter table %I.memory enable row level security', object_schema);
        execute format('alter table %I.camera_back enable row level security', object_schema);
        execute format('alter table %I.camera_front enable row level security', object_schema);
        execute format('alter table %I.features enable row level security', object_schema);
        execute format('alter table %I.battery enable row level security', object_schema);
    end loop;

    alter table warehouse.ingest_runs enable row level security;
    alter table warehouse.raw_ingest enable row level security;
    alter table warehouse.price_history enable row level security;
    alter table warehouse.etl_rejects enable row level security;
end
$security$;

commit;
