-- MobileInfoAnalytics database schema v1
-- Target: Amazon Redshift (provisioned or Serverless).
--
-- GSMArena is the canonical product authority.  data_snapshot is a release
-- year and data_snapshot_detail preserves the available month precision as
-- MM or MM-DD.  Marketplace tables receive both values only through their
-- product_id relationship to original.central_info.
--
-- Redshift primary, unique, and foreign-key constraints are informational.
-- db/functions_v1.sql therefore performs the matching, de-duplication, and
-- referential-integrity work before inserting rows.

CREATE SCHEMA IF NOT EXISTS original;
CREATE SCHEMA IF NOT EXISTS daraz;
CREATE SCHEMA IF NOT EXISTS mymobile;
CREATE SCHEMA IF NOT EXISTS mega;
CREATE SCHEMA IF NOT EXISTS whatamobile;
CREATE SCHEMA IF NOT EXISTS whatmobile;
CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS warehouse;
CREATE SCHEMA IF NOT EXISTS analytics;
CREATE SCHEMA IF NOT EXISTS etl;

-- -------------------------------------------------------------------------
-- Canonical GSMArena product tables
-- -------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS original.central_info (
    serial_number BIGINT GENERATED BY DEFAULT AS IDENTITY(1,1) NOT NULL,
    data_snapshot SMALLINT NOT NULL
        DEFAULT (DATE_PART(year, CURRENT_DATE)),
    data_snapshot_detail VARCHAR(5) NOT NULL
        DEFAULT TO_CHAR(CURRENT_DATE, 'MM-DD'),
    snapshot_source VARCHAR(16) NOT NULL DEFAULT 'current_utc',
    name VARCHAR(1024) NOT NULL,
    url VARCHAR(2048) NOT NULL,
    network_id BIGINT NOT NULL,
    launch_id BIGINT NOT NULL,
    body_id BIGINT NOT NULL,
    display_id BIGINT NOT NULL,
    platform_id BIGINT NOT NULL,
    memory_id BIGINT NOT NULL,
    camera_back_id BIGINT NOT NULL,
    camera_front_id BIGINT NOT NULL,
    sound_loudspeaker VARCHAR(65535),
    sound_cable_jack BOOLEAN NOT NULL DEFAULT TRUE,
    features_id BIGINT NOT NULL,
    battery_id BIGINT NOT NULL,
    colors SUPER,
    weight VARCHAR(1024) NOT NULL DEFAULT 'Weight Unknown',
    price SUPER NOT NULL,
    PRIMARY KEY (serial_number),
    UNIQUE (name),
    UNIQUE (url),
    UNIQUE (network_id),
    UNIQUE (launch_id),
    UNIQUE (body_id),
    UNIQUE (display_id),
    UNIQUE (platform_id),
    UNIQUE (memory_id),
    UNIQUE (camera_back_id),
    UNIQUE (camera_front_id),
    UNIQUE (features_id),
    UNIQUE (battery_id)
) DISTSTYLE AUTO SORTKEY (data_snapshot, name);

CREATE TABLE IF NOT EXISTS original.network (
    network_id BIGINT NOT NULL PRIMARY KEY
        REFERENCES original.central_info(network_id),
    "2g" BOOLEAN NOT NULL DEFAULT TRUE,
    "3g" BOOLEAN NOT NULL DEFAULT TRUE,
    "4g" BOOLEAN NOT NULL DEFAULT FALSE,
    "5g" BOOLEAN NOT NULL DEFAULT TRUE
) DISTSTYLE AUTO;

CREATE TABLE IF NOT EXISTS original.launch (
    launch_id BIGINT NOT NULL PRIMARY KEY
        REFERENCES original.central_info(launch_id),
    announced VARCHAR(65535),
    status VARCHAR(65535)
) DISTSTYLE AUTO;

CREATE TABLE IF NOT EXISTS original.body (
    body_id BIGINT NOT NULL PRIMARY KEY
        REFERENCES original.central_info(body_id),
    dimensions VARCHAR(65535),
    weight VARCHAR(65535),
    build VARCHAR(65535),
    sim VARCHAR(65535),
    protection VARCHAR(65535)
) DISTSTYLE AUTO;

CREATE TABLE IF NOT EXISTS original.display (
    display_id BIGINT NOT NULL PRIMARY KEY
        REFERENCES original.central_info(display_id),
    type VARCHAR(65535),
    size VARCHAR(65535),
    resolution VARCHAR(65535),
    protection VARCHAR(65535)
) DISTSTYLE AUTO;

CREATE TABLE IF NOT EXISTS original.platform (
    platform_id BIGINT NOT NULL PRIMARY KEY
        REFERENCES original.central_info(platform_id),
    os VARCHAR(65535),
    chipset VARCHAR(65535),
    cpu VARCHAR(65535),
    gpu VARCHAR(65535)
) DISTSTYLE AUTO;

CREATE TABLE IF NOT EXISTS original.memory (
    memory_id BIGINT NOT NULL PRIMARY KEY
        REFERENCES original.central_info(memory_id),
    card_slot VARCHAR(65535),
    technology VARCHAR(65535),
    types SUPER
) DISTSTYLE AUTO;

CREATE TABLE IF NOT EXISTS original.camera_back (
    camera_back_id BIGINT NOT NULL PRIMARY KEY
        REFERENCES original.central_info(camera_back_id),
    specifications SUPER,
    features VARCHAR(65535),
    video SUPER
) DISTSTYLE AUTO;

CREATE TABLE IF NOT EXISTS original.camera_front (
    camera_front_id BIGINT NOT NULL PRIMARY KEY
        REFERENCES original.central_info(camera_front_id),
    specifications SUPER,
    features VARCHAR(65535),
    video SUPER
) DISTSTYLE AUTO;

CREATE TABLE IF NOT EXISTS original.features (
    features_id BIGINT NOT NULL PRIMARY KEY
        REFERENCES original.central_info(features_id),
    wlan VARCHAR(65535),
    bluetooth VARCHAR(65535),
    positioning VARCHAR(65535),
    nfc BOOLEAN NOT NULL DEFAULT FALSE,
    infrared_port BOOLEAN NOT NULL DEFAULT FALSE,
    radio BOOLEAN NOT NULL DEFAULT TRUE,
    usb VARCHAR(65535),
    back_finger_print BOOLEAN NOT NULL DEFAULT FALSE,
    side_finger_print BOOLEAN NOT NULL DEFAULT FALSE,
    in_display_finger_print BOOLEAN NOT NULL DEFAULT FALSE,
    sensors VARCHAR(65535)
) DISTSTYLE AUTO;

CREATE TABLE IF NOT EXISTS original.battery (
    battery_id BIGINT NOT NULL PRIMARY KEY
        REFERENCES original.central_info(battery_id),
    capacity VARCHAR(65535),
    wireless_charging BOOLEAN NOT NULL DEFAULT FALSE,
    charging SUPER
) DISTSTYLE AUTO;

-- -------------------------------------------------------------------------
-- Repeated marketplace schema.  This helper is run once per allowlisted
-- schema and then removed.  Static names are supplied only by this migration.
-- -------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE etl.create_source_tables(p_schema VARCHAR)
AS $$
DECLARE
    s VARCHAR(128);
BEGIN
    IF p_schema NOT IN ('daraz', 'mymobile', 'mega', 'whatamobile', 'whatmobile') THEN
        RAISE EXCEPTION 'Unsupported source schema: %', p_schema;
    END IF;
    s := QUOTE_IDENT(p_schema);

    EXECUTE 'CREATE TABLE IF NOT EXISTS ' || s || '.central_info (
        serial_number BIGINT GENERATED BY DEFAULT AS IDENTITY(1,1) NOT NULL,
        product_id BIGINT NOT NULL REFERENCES original.central_info(serial_number),
        instance_number INTEGER NOT NULL,
        PRIMARY KEY (serial_number),
        UNIQUE (product_id, instance_number)
    ) DISTSTYLE AUTO SORTKEY (product_id, instance_number)';

    EXECUTE 'CREATE TABLE IF NOT EXISTS ' || s || '.secondary_info (
        serial_number BIGINT NOT NULL PRIMARY KEY REFERENCES ' || s || '.central_info(serial_number),
        data_snapshot SMALLINT NOT NULL,
        data_snapshot_detail VARCHAR(5) NOT NULL,
        name VARCHAR(1024) NOT NULL,
        url VARCHAR(2048) NOT NULL UNIQUE,
        network_id BIGINT NOT NULL UNIQUE,
        launch_id BIGINT NOT NULL UNIQUE,
        body_id BIGINT NOT NULL UNIQUE,
        display_id BIGINT NOT NULL UNIQUE,
        platform_id BIGINT NOT NULL UNIQUE,
        memory_id BIGINT NOT NULL UNIQUE,
        camera_back_id BIGINT NOT NULL UNIQUE,
        camera_front_id BIGINT NOT NULL UNIQUE,
        sound_loudspeaker VARCHAR(65535),
        sound_cable_jack BOOLEAN NOT NULL DEFAULT TRUE,
        features_id BIGINT NOT NULL UNIQUE,
        battery_id BIGINT NOT NULL UNIQUE,
        colors SUPER,
        weight VARCHAR(1024) NOT NULL DEFAULT ''Weight Unknown'',
        price SUPER NOT NULL
    ) DISTSTYLE AUTO SORTKEY (data_snapshot, name)';

    EXECUTE 'CREATE TABLE IF NOT EXISTS ' || s || '.network (
        network_id BIGINT NOT NULL PRIMARY KEY REFERENCES ' || s || '.secondary_info(network_id),
        "2g" BOOLEAN NOT NULL DEFAULT TRUE,
        "3g" BOOLEAN NOT NULL DEFAULT TRUE,
        "4g" BOOLEAN NOT NULL DEFAULT FALSE,
        "5g" BOOLEAN NOT NULL DEFAULT TRUE
    ) DISTSTYLE AUTO';

    EXECUTE 'CREATE TABLE IF NOT EXISTS ' || s || '.launch (
        launch_id BIGINT NOT NULL PRIMARY KEY REFERENCES ' || s || '.secondary_info(launch_id),
        announced VARCHAR(65535), status VARCHAR(65535)
    ) DISTSTYLE AUTO';

    EXECUTE 'CREATE TABLE IF NOT EXISTS ' || s || '.body (
        body_id BIGINT NOT NULL PRIMARY KEY REFERENCES ' || s || '.secondary_info(body_id),
        dimensions VARCHAR(65535), weight VARCHAR(65535), build VARCHAR(65535),
        sim VARCHAR(65535), protection VARCHAR(65535)
    ) DISTSTYLE AUTO';

    EXECUTE 'CREATE TABLE IF NOT EXISTS ' || s || '.display (
        display_id BIGINT NOT NULL PRIMARY KEY REFERENCES ' || s || '.secondary_info(display_id),
        type VARCHAR(65535), size VARCHAR(65535), resolution VARCHAR(65535),
        protection VARCHAR(65535)
    ) DISTSTYLE AUTO';

    EXECUTE 'CREATE TABLE IF NOT EXISTS ' || s || '.platform (
        platform_id BIGINT NOT NULL PRIMARY KEY REFERENCES ' || s || '.secondary_info(platform_id),
        os VARCHAR(65535), chipset VARCHAR(65535), cpu VARCHAR(65535), gpu VARCHAR(65535)
    ) DISTSTYLE AUTO';

    EXECUTE 'CREATE TABLE IF NOT EXISTS ' || s || '.memory (
        memory_id BIGINT NOT NULL PRIMARY KEY REFERENCES ' || s || '.secondary_info(memory_id),
        card_slot VARCHAR(65535), technology VARCHAR(65535), types SUPER
    ) DISTSTYLE AUTO';

    EXECUTE 'CREATE TABLE IF NOT EXISTS ' || s || '.camera_back (
        camera_back_id BIGINT NOT NULL PRIMARY KEY REFERENCES ' || s || '.secondary_info(camera_back_id),
        specifications SUPER, features VARCHAR(65535), video SUPER
    ) DISTSTYLE AUTO';

    EXECUTE 'CREATE TABLE IF NOT EXISTS ' || s || '.camera_front (
        camera_front_id BIGINT NOT NULL PRIMARY KEY REFERENCES ' || s || '.secondary_info(camera_front_id),
        specifications SUPER, features VARCHAR(65535), video SUPER
    ) DISTSTYLE AUTO';

    EXECUTE 'CREATE TABLE IF NOT EXISTS ' || s || '.features (
        features_id BIGINT NOT NULL PRIMARY KEY REFERENCES ' || s || '.secondary_info(features_id),
        wlan VARCHAR(65535), bluetooth VARCHAR(65535), positioning VARCHAR(65535),
        nfc BOOLEAN NOT NULL DEFAULT FALSE,
        infrared_port BOOLEAN NOT NULL DEFAULT FALSE,
        radio BOOLEAN NOT NULL DEFAULT TRUE,
        usb VARCHAR(65535),
        back_finger_print BOOLEAN NOT NULL DEFAULT FALSE,
        side_finger_print BOOLEAN NOT NULL DEFAULT FALSE,
        in_display_finger_print BOOLEAN NOT NULL DEFAULT FALSE,
        sensors VARCHAR(65535)
    ) DISTSTYLE AUTO';

    EXECUTE 'CREATE TABLE IF NOT EXISTS ' || s || '.battery (
        battery_id BIGINT NOT NULL PRIMARY KEY REFERENCES ' || s || '.secondary_info(battery_id),
        capacity VARCHAR(65535),
        wireless_charging BOOLEAN NOT NULL DEFAULT FALSE,
        charging SUPER
    ) DISTSTYLE AUTO';
END;
$$ LANGUAGE plpgsql;

CALL etl.create_source_tables('daraz');
CALL etl.create_source_tables('mymobile');
CALL etl.create_source_tables('mega');
CALL etl.create_source_tables('whatamobile');
CALL etl.create_source_tables('whatmobile');
DROP PROCEDURE etl.create_source_tables(VARCHAR);

-- -------------------------------------------------------------------------
-- COPY landing tables.  Column order exactly matches jsonToCsv.RECORD_FIELDS.
-- -------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS staging.phone_records (
    record_key CHAR(64),
    source_schema VARCHAR(32),
    source_site VARCHAR(255),
    source_file VARCHAR(2048),
    source_url VARCHAR(2048),
    url_recovery VARCHAR(32),
    data_snapshot SMALLINT,
    data_snapshot_detail VARCHAR(5),
    snapshot_source VARCHAR(32),
    mobile_name VARCHAR(1024),
    network_2g BOOLEAN,
    network_3g BOOLEAN,
    network_4g BOOLEAN,
    network_5g BOOLEAN,
    launch_announced VARCHAR(65535),
    launch_status VARCHAR(65535),
    body_dimensions VARCHAR(65535),
    body_weight VARCHAR(65535),
    body_build VARCHAR(65535),
    body_sim VARCHAR(65535),
    body_protection VARCHAR(65535),
    display_type VARCHAR(65535),
    display_size VARCHAR(65535),
    display_resolution VARCHAR(65535),
    display_protection VARCHAR(65535),
    platform_os VARCHAR(65535),
    platform_chipset VARCHAR(65535),
    platform_cpu VARCHAR(65535),
    platform_gpu VARCHAR(65535),
    memory_card_slot VARCHAR(65535),
    memory_types_json SUPER,
    memory_technology VARCHAR(65535),
    main_camera_specifications_json SUPER,
    main_camera_features VARCHAR(65535),
    main_camera_video_json SUPER,
    selfie_camera_specifications_json SUPER,
    selfie_camera_features VARCHAR(65535),
    selfie_camera_video_json SUPER,
    sound_loudspeaker VARCHAR(65535),
    sound_cable_jack BOOLEAN,
    features_wlan VARCHAR(65535),
    features_bluetooth VARCHAR(65535),
    features_positioning VARCHAR(65535),
    features_nfc BOOLEAN,
    features_infrared_port BOOLEAN,
    features_radio BOOLEAN,
    features_usb VARCHAR(65535),
    features_back_finger_print BOOLEAN,
    features_side_finger_print BOOLEAN,
    features_in_display_finger_print BOOLEAN,
    features_sensors VARCHAR(65535),
    battery_capacity VARCHAR(65535),
    battery_wireless_charging BOOLEAN,
    battery_charging_json SUPER,
    colors_json SUPER,
    exposure_weight VARCHAR(1024),
    prices_json SUPER,
    completeness_score DECIMAL(6,5),
    file_sha256 CHAR(64),
    payload_json SUPER
) BACKUP NO DISTSTYLE AUTO SORTKEY (source_schema, source_url);

CREATE TABLE IF NOT EXISTS staging.product_map (
    source_schema VARCHAR(32),
    source_url VARCHAR(2048),
    product_id BIGINT
) BACKUP NO DISTSTYLE ALL;

-- -------------------------------------------------------------------------
-- Durable landing/audit facts and analytical price history
-- -------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS warehouse.raw_ingest (
    raw_id BIGINT GENERATED BY DEFAULT AS IDENTITY(1,1) NOT NULL,
    record_key CHAR(64) NOT NULL,
    source_schema VARCHAR(32) NOT NULL,
    source_url VARCHAR(2048) NOT NULL,
    source_file VARCHAR(2048) NOT NULL,
    data_snapshot SMALLINT,
    data_snapshot_detail VARCHAR(5),
    snapshot_source VARCHAR(32),
    file_sha256 CHAR(64) NOT NULL,
    completeness_score DECIMAL(6,5),
    payload SUPER NOT NULL,
    loaded_at TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (raw_id),
    UNIQUE (source_schema, source_url, file_sha256)
) DISTSTYLE AUTO SORTKEY (loaded_at, source_schema);

CREATE TABLE IF NOT EXISTS warehouse.price_history (
    price_id BIGINT GENERATED BY DEFAULT AS IDENTITY(1,1) NOT NULL,
    product_id BIGINT NOT NULL REFERENCES original.central_info(serial_number),
    source_schema VARCHAR(32) NOT NULL,
    source_serial_number BIGINT NOT NULL,
    source_url VARCHAR(2048) NOT NULL,
    file_sha256 CHAR(64) NOT NULL,
    observed_at TIMESTAMP NOT NULL DEFAULT GETDATE(),
    data_snapshot SMALLINT NOT NULL,
    data_snapshot_detail VARCHAR(5) NOT NULL,
    amount DECIMAL(18,2) NOT NULL,
    currency_code VARCHAR(3),
    PRIMARY KEY (price_id)
) DISTSTYLE AUTO SORTKEY (product_id, observed_at);

CREATE TABLE IF NOT EXISTS warehouse.etl_rejects (
    reject_id BIGINT GENERATED BY DEFAULT AS IDENTITY(1,1) NOT NULL,
    record_key CHAR(64),
    source_schema VARCHAR(32) NOT NULL,
    source_url VARCHAR(2048),
    source_file VARCHAR(2048),
    reason_code VARCHAR(64) NOT NULL,
    reason_detail VARCHAR(65535),
    payload SUPER,
    rejected_at TIMESTAMP NOT NULL DEFAULT GETDATE(),
    resolved_at TIMESTAMP,
    resolution_detail VARCHAR(65535),
    PRIMARY KEY (reject_id)
) DISTSTYLE AUTO SORTKEY (rejected_at, source_schema);

CREATE TABLE IF NOT EXISTS warehouse.load_runs (
    run_id BIGINT GENERATED BY DEFAULT AS IDENTITY(1,1) NOT NULL,
    started_at TIMESTAMP NOT NULL DEFAULT GETDATE(),
    finished_at TIMESTAMP,
    staged_count BIGINT NOT NULL DEFAULT 0,
    loaded_count BIGINT NOT NULL DEFAULT 0,
    rejected_count BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'running',
    PRIMARY KEY (run_id)
) DISTSTYLE AUTO SORTKEY (started_at);
