-- =============================================================================
-- MobileInfoAnalytics - Supabase PostgreSQL Database Schema (v3)
-- Target: PostgreSQL 15+ / Supabase
-- Architecture: 4 Schemas (catalog, specs, listings, metadata) + staging & analytics
-- Based on template_v2 specification and multi-source cross-linking design.
-- Includes full Row Level Security (RLS) policies and Role Permissions.
-- =============================================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm"; -- For fuzzy name and alias matching

-- -----------------------------------------------------------------------------
-- Schemas
-- -----------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS catalog;   -- Source-independent product & brand identity
CREATE SCHEMA IF NOT EXISTS specs;     -- Canonical GSMArena / best-known specifications
CREATE SCHEMA IF NOT EXISTS listings;  -- All marketplace listings with full per-listing specs
CREATE SCHEMA IF NOT EXISTS metadata;  -- Ingestion audit runs, rejects & quality scoring
CREATE SCHEMA IF NOT EXISTS staging;   -- Raw JSON staging & landing tables
CREATE SCHEMA IF NOT EXISTS analytics; -- Stable analytical views for comparison & insights
CREATE SCHEMA IF NOT EXISTS etl;       -- Ingestion functions, procedures & pipelines

-- =============================================================================
-- 1. SCHEMA: catalog (Product & Brand Identity)
-- =============================================================================

-- Table: catalog.companies (Manufacturer / Brand Master)
CREATE TABLE IF NOT EXISTS catalog.companies (
    company_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name TEXT NOT NULL,
    company_slug TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE catalog.companies IS 'Normalized mobile brand/manufacturer master list.';
COMMENT ON COLUMN catalog.companies.company_slug IS 'URL-safe lowercased slug (e.g., xiaomi, samsung, apple).';

-- Table: catalog.products (Central Abstract Product Hub)
CREATE TABLE IF NOT EXISTS catalog.products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES catalog.companies(company_id) ON DELETE RESTRICT,
    mobile_name TEXT NOT NULL,
    product_slug TEXT NOT NULL UNIQUE,
    created_by_source TEXT NOT NULL DEFAULT 'unknown',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE catalog.products IS 'The abstract central mobile phone entity. Independent of any single website.';
COMMENT ON COLUMN catalog.products.product_slug IS 'Universal matching slug (e.g., xiaomi-redmi-note-14-4g).';
COMMENT ON COLUMN catalog.products.created_by_source IS 'Tracks which site (e.g. gsmarena, daraz, whatmobile) first discovered this phone.';

-- Table: catalog.product_aliases (Cross-Site Name Disambiguation & Alias Mapping)
CREATE TABLE IF NOT EXISTS catalog.product_aliases (
    alias_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES catalog.products(product_id) ON DELETE CASCADE,
    alias_name TEXT NOT NULL,
    alias_slug TEXT NOT NULL UNIQUE,
    source_domain TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE catalog.product_aliases IS 'Alternative titles across websites mapped to the canonical product_id.';

CREATE INDEX IF NOT EXISTS idx_products_company_id ON catalog.products(company_id);
CREATE INDEX IF NOT EXISTS idx_products_slug ON catalog.products(product_slug);
CREATE INDEX IF NOT EXISTS idx_aliases_product_id ON catalog.product_aliases(product_id);
CREATE INDEX IF NOT EXISTS idx_aliases_slug ON catalog.product_aliases(alias_slug);


-- =============================================================================
-- 2. SCHEMA: specs (Canonical / Best-Known Specifications)
-- =============================================================================

-- Table: specs.product_specs (Central Canonical Header)
CREATE TABLE IF NOT EXISTS specs.product_specs (
    product_id BIGINT PRIMARY KEY REFERENCES catalog.products(product_id) ON DELETE CASCADE,
    release_year SMALLINT NOT NULL DEFAULT 2014,
    release_month VARCHAR(3) NOT NULL DEFAULT 'DEC',
    release_day SMALLINT,
    announced_text TEXT,
    status_text TEXT,
    colors TEXT[] DEFAULT '{}',
    has_loudspeaker BOOLEAN NOT NULL DEFAULT TRUE,
    has_3_5mm_jack BOOLEAN NOT NULL DEFAULT TRUE,
    specs_source TEXT NOT NULL DEFAULT 'gsmarena.com',
    last_updated TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE specs.product_specs IS 'Canonical product specs header (1:1 with catalog.products).';

-- Table: specs.spec_network
CREATE TABLE IF NOT EXISTS specs.spec_network (
    product_id BIGINT PRIMARY KEY REFERENCES specs.product_specs(product_id) ON DELETE CASCADE,
    supports_2g BOOLEAN NOT NULL DEFAULT TRUE,
    supports_3g BOOLEAN NOT NULL DEFAULT TRUE,
    supports_4g BOOLEAN NOT NULL DEFAULT FALSE,
    supports_5g BOOLEAN NOT NULL DEFAULT FALSE
);

-- Table: specs.spec_body
CREATE TABLE IF NOT EXISTS specs.spec_body (
    product_id BIGINT PRIMARY KEY REFERENCES specs.product_specs(product_id) ON DELETE CASCADE,
    dim_length_mm NUMERIC(6,2) NOT NULL DEFAULT 50.0,
    dim_width_mm NUMERIC(6,2) NOT NULL DEFAULT 50.0,
    dim_depth_mm NUMERIC(5,2) NOT NULL DEFAULT 5.0,
    weight_grams NUMERIC(6,2) NOT NULL DEFAULT 25.0,
    build_materials TEXT,
    has_normal_sim BOOLEAN NOT NULL DEFAULT FALSE,
    has_nano_sim BOOLEAN NOT NULL DEFAULT TRUE,
    has_esim BOOLEAN NOT NULL DEFAULT FALSE,
    ip_rating TEXT,
    is_water_resistant BOOLEAN NOT NULL DEFAULT FALSE,
    is_dust_resistant BOOLEAN NOT NULL DEFAULT TRUE
);

-- Table: specs.spec_display
CREATE TABLE IF NOT EXISTS specs.spec_display (
    product_id BIGINT PRIMARY KEY REFERENCES specs.product_specs(product_id) ON DELETE CASCADE,
    screen_technology TEXT NOT NULL DEFAULT 'LCD', -- 'CRT', 'LCD', 'LED', 'AMOLED', 'OLED'
    refresh_rate_hz INT NOT NULL DEFAULT 60,
    peak_brightness_nits INT NOT NULL DEFAULT 60,
    resolution_width INT NOT NULL DEFAULT 240,
    resolution_height INT NOT NULL DEFAULT 240,
    aspect_ratio TEXT,
    pixel_density_ppi INT,
    screen_protection TEXT
);

-- Table: specs.spec_platform
CREATE TABLE IF NOT EXISTS specs.spec_platform (
    product_id BIGINT PRIMARY KEY REFERENCES specs.product_specs(product_id) ON DELETE CASCADE,
    operating_system TEXT,
    chipset_name TEXT,
    chipset_node_nm INT,
    cpu_description TEXT,
    gpu_name TEXT
);

-- Table: specs.spec_memory
CREATE TABLE IF NOT EXISTS specs.spec_memory (
    product_id BIGINT PRIMARY KEY REFERENCES specs.product_specs(product_id) ON DELETE CASCADE,
    card_slot TEXT,
    storage_ram_variants JSONB NOT NULL DEFAULT '[[0,0]]'::jsonb, -- e.g. [[128, 6], [256, 8]]
    technology TEXT
);

-- Table: specs.spec_camera_main
CREATE TABLE IF NOT EXISTS specs.spec_camera_main (
    product_id BIGINT PRIMARY KEY REFERENCES specs.product_specs(product_id) ON DELETE CASCADE,
    sensor_specs TEXT[] DEFAULT '{}',
    photo_features TEXT,
    video_modes TEXT[] DEFAULT '{}'
);

-- Table: specs.spec_camera_selfie
CREATE TABLE IF NOT EXISTS specs.spec_camera_selfie (
    product_id BIGINT PRIMARY KEY REFERENCES specs.product_specs(product_id) ON DELETE CASCADE,
    sensor_specs TEXT[] DEFAULT '{}',
    video_modes TEXT[] DEFAULT '{}'
);

-- Table: specs.spec_connectivity
CREATE TABLE IF NOT EXISTS specs.spec_connectivity (
    product_id BIGINT PRIMARY KEY REFERENCES specs.product_specs(product_id) ON DELETE CASCADE,
    wifi_standards TEXT,
    bluetooth_version TEXT,
    positioning_systems TEXT,
    has_nfc BOOLEAN NOT NULL DEFAULT FALSE,
    has_infrared BOOLEAN NOT NULL DEFAULT FALSE,
    has_fm_radio BOOLEAN NOT NULL DEFAULT TRUE,
    has_usb_a BOOLEAN NOT NULL DEFAULT FALSE,
    has_usb_b BOOLEAN NOT NULL DEFAULT FALSE,
    has_micro_usb BOOLEAN NOT NULL DEFAULT TRUE,
    has_usb_c BOOLEAN NOT NULL DEFAULT FALSE,
    has_fp_rear BOOLEAN NOT NULL DEFAULT FALSE,
    has_fp_side BOOLEAN NOT NULL DEFAULT FALSE,
    has_fp_under_display BOOLEAN NOT NULL DEFAULT FALSE
);

-- Table: specs.spec_battery
CREATE TABLE IF NOT EXISTS specs.spec_battery (
    product_id BIGINT PRIMARY KEY REFERENCES specs.product_specs(product_id) ON DELETE CASCADE,
    capacity_mah INT NOT NULL DEFAULT 0,
    has_wireless_charging BOOLEAN NOT NULL DEFAULT FALSE,
    charging_specs TEXT[] DEFAULT '{}'
);


-- =============================================================================
-- 3. SCHEMA: metadata (Audit Runs, Logs & Reject Tracking)
-- =============================================================================

-- Table: metadata.scrape_runs
CREATE TABLE IF NOT EXISTS metadata.scrape_runs (
    run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_domain TEXT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at TIMESTAMPTZ,
    records_processed INT NOT NULL DEFAULT 0,
    records_succeeded INT NOT NULL DEFAULT 0,
    records_failed INT NOT NULL DEFAULT 0,
    run_status TEXT NOT NULL DEFAULT 'running'
);

-- Table: metadata.etl_rejects
CREATE TABLE IF NOT EXISTS metadata.etl_rejects (
    reject_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scrape_run_id BIGINT REFERENCES metadata.scrape_runs(run_id) ON DELETE SET NULL,
    source_domain TEXT NOT NULL,
    source_url TEXT,
    source_file TEXT,
    reject_reason TEXT NOT NULL,
    reject_detail TEXT,
    raw_payload JSONB,
    rejected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at TIMESTAMPTZ,
    resolution_detail TEXT
);

-- Table: metadata.data_quality
CREATE TABLE IF NOT EXISTS metadata.data_quality (
    score_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES catalog.products(product_id) ON DELETE CASCADE,
    listing_id BIGINT,
    source_domain TEXT NOT NULL,
    completeness_pct NUMERIC(5,2) NOT NULL,
    fields_populated INT NOT NULL,
    fields_total INT NOT NULL,
    scored_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =============================================================================
-- 4. SCHEMA: listings (Marketplace Listings & Individual Scraped Specs)
-- =============================================================================

-- Table: listings.market_listings (Master Listing Record)
CREATE TABLE IF NOT EXISTS listings.market_listings (
    listing_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES catalog.products(product_id) ON DELETE CASCADE,
    instance_number INT NOT NULL DEFAULT 1,
    source_domain TEXT NOT NULL, -- 'daraz.pk', 'whatmobile.com.pk', 'mega.pk', 'mymobile.pk', 'gsmarena.com'
    source_url TEXT NOT NULL UNIQUE,
    listing_title TEXT NOT NULL,
    announced_text TEXT,
    status_text TEXT,
    release_year SMALLINT NOT NULL DEFAULT 2014,
    release_month VARCHAR(3) NOT NULL DEFAULT 'DEC',
    release_day SMALLINT,
    colors TEXT[] DEFAULT '{}',
    has_loudspeaker BOOLEAN NOT NULL DEFAULT TRUE,
    has_3_5mm_jack BOOLEAN NOT NULL DEFAULT TRUE,
    raw_payload JSONB,
    scrape_run_id BIGINT REFERENCES metadata.scrape_runs(run_id) ON DELETE SET NULL,
    scraped_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_product_source_instance UNIQUE (product_id, source_domain, instance_number)
);

COMMENT ON TABLE listings.market_listings IS 'Every individual scraped listing per website with instance tracking.';
COMMENT ON COLUMN listings.market_listings.instance_number IS 'Instance sequence per (product, source_domain).';

-- Table: listings.listing_prices (Structured Prices with Currency)
CREATE TABLE IF NOT EXISTS listings.listing_prices (
    price_entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT NOT NULL REFERENCES listings.market_listings(listing_id) ON DELETE CASCADE,
    currency_code VARCHAR(3) NOT NULL DEFAULT 'PKR', -- 'USD', 'EUR', 'GBP', 'PKR'
    amount NUMERIC(14,2) NOT NULL,
    price_index INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_listing_currency_idx UNIQUE (listing_id, currency_code, price_index)
);

-- Table: listings.listing_network
CREATE TABLE IF NOT EXISTS listings.listing_network (
    listing_id BIGINT PRIMARY KEY REFERENCES listings.market_listings(listing_id) ON DELETE CASCADE,
    supports_2g BOOLEAN NOT NULL DEFAULT TRUE,
    supports_3g BOOLEAN NOT NULL DEFAULT TRUE,
    supports_4g BOOLEAN NOT NULL DEFAULT FALSE,
    supports_5g BOOLEAN NOT NULL DEFAULT FALSE
);

-- Table: listings.listing_body
CREATE TABLE IF NOT EXISTS listings.listing_body (
    listing_id BIGINT PRIMARY KEY REFERENCES listings.market_listings(listing_id) ON DELETE CASCADE,
    dim_length_mm NUMERIC(6,2) NOT NULL DEFAULT 50.0,
    dim_width_mm NUMERIC(6,2) NOT NULL DEFAULT 50.0,
    dim_depth_mm NUMERIC(5,2) NOT NULL DEFAULT 5.0,
    weight_grams NUMERIC(6,2) NOT NULL DEFAULT 25.0,
    build_materials TEXT,
    has_normal_sim BOOLEAN NOT NULL DEFAULT FALSE,
    has_nano_sim BOOLEAN NOT NULL DEFAULT TRUE,
    has_esim BOOLEAN NOT NULL DEFAULT FALSE,
    ip_rating TEXT,
    is_water_resistant BOOLEAN NOT NULL DEFAULT FALSE,
    is_dust_resistant BOOLEAN NOT NULL DEFAULT TRUE
);

-- Table: listings.listing_display
CREATE TABLE IF NOT EXISTS listings.listing_display (
    listing_id BIGINT PRIMARY KEY REFERENCES listings.market_listings(listing_id) ON DELETE CASCADE,
    screen_technology TEXT NOT NULL DEFAULT 'LCD',
    refresh_rate_hz INT NOT NULL DEFAULT 60,
    peak_brightness_nits INT NOT NULL DEFAULT 60,
    resolution_width INT NOT NULL DEFAULT 240,
    resolution_height INT NOT NULL DEFAULT 240,
    aspect_ratio TEXT,
    pixel_density_ppi INT,
    screen_protection TEXT
);

-- Table: listings.listing_platform
CREATE TABLE IF NOT EXISTS listings.listing_platform (
    listing_id BIGINT PRIMARY KEY REFERENCES listings.market_listings(listing_id) ON DELETE CASCADE,
    operating_system TEXT,
    chipset_name TEXT,
    chipset_node_nm INT,
    cpu_description TEXT,
    gpu_name TEXT
);

-- Table: listings.listing_memory
CREATE TABLE IF NOT EXISTS listings.listing_memory (
    listing_id BIGINT PRIMARY KEY REFERENCES listings.market_listings(listing_id) ON DELETE CASCADE,
    card_slot TEXT,
    storage_ram_variants JSONB NOT NULL DEFAULT '[[0,0]]'::jsonb,
    technology TEXT
);

-- Table: listings.listing_camera_main
CREATE TABLE IF NOT EXISTS listings.listing_camera_main (
    listing_id BIGINT PRIMARY KEY REFERENCES listings.market_listings(listing_id) ON DELETE CASCADE,
    sensor_specs TEXT[] DEFAULT '{}',
    photo_features TEXT,
    video_modes TEXT[] DEFAULT '{}'
);

-- Table: listings.listing_camera_selfie
CREATE TABLE IF NOT EXISTS listings.listing_camera_selfie (
    listing_id BIGINT PRIMARY KEY REFERENCES listings.market_listings(listing_id) ON DELETE CASCADE,
    sensor_specs TEXT[] DEFAULT '{}',
    video_modes TEXT[] DEFAULT '{}'
);

-- Table: listings.listing_connectivity
CREATE TABLE IF NOT EXISTS listings.listing_connectivity (
    listing_id BIGINT PRIMARY KEY REFERENCES listings.market_listings(listing_id) ON DELETE CASCADE,
    wifi_standards TEXT,
    bluetooth_version TEXT,
    positioning_systems TEXT,
    has_nfc BOOLEAN NOT NULL DEFAULT FALSE,
    has_infrared BOOLEAN NOT NULL DEFAULT FALSE,
    has_fm_radio BOOLEAN NOT NULL DEFAULT TRUE,
    has_usb_a BOOLEAN NOT NULL DEFAULT FALSE,
    has_usb_b BOOLEAN NOT NULL DEFAULT FALSE,
    has_micro_usb BOOLEAN NOT NULL DEFAULT TRUE,
    has_usb_c BOOLEAN NOT NULL DEFAULT FALSE,
    has_fp_rear BOOLEAN NOT NULL DEFAULT FALSE,
    has_fp_side BOOLEAN NOT NULL DEFAULT FALSE,
    has_fp_under_display BOOLEAN NOT NULL DEFAULT FALSE
);

-- Table: listings.listing_battery
CREATE TABLE IF NOT EXISTS listings.listing_battery (
    listing_id BIGINT PRIMARY KEY REFERENCES listings.market_listings(listing_id) ON DELETE CASCADE,
    capacity_mah INT NOT NULL DEFAULT 0,
    has_wireless_charging BOOLEAN NOT NULL DEFAULT FALSE,
    charging_specs TEXT[] DEFAULT '{}'
);

-- Foreign key & indexes for listings
CREATE INDEX IF NOT EXISTS idx_listings_product_id ON listings.market_listings(product_id);
CREATE INDEX IF NOT EXISTS idx_listings_source_domain ON listings.market_listings(source_domain);
CREATE INDEX IF NOT EXISTS idx_listings_url ON listings.market_listings(source_url);
CREATE INDEX IF NOT EXISTS idx_listing_prices_listing_id ON listings.listing_prices(listing_id);
CREATE INDEX IF NOT EXISTS idx_listing_prices_currency ON listings.listing_prices(currency_code, amount);


-- =============================================================================
-- 5. SCHEMA: staging (Landing Table for Batch File Loading)
-- =============================================================================

CREATE TABLE IF NOT EXISTS staging.raw_json_records (
    staging_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_key TEXT,
    source_domain TEXT NOT NULL,
    source_file TEXT NOT NULL,
    source_url TEXT,
    payload JSONB NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'pending' -- 'pending', 'processed', 'failed'
);

CREATE INDEX IF NOT EXISTS idx_staging_status ON staging.raw_json_records(status);


-- =============================================================================
-- 6. ROW LEVEL SECURITY (RLS) ACTIVATION & POLICIES
-- =============================================================================

-- Enable Row Level Security across all tables
ALTER TABLE catalog.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalog.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalog.product_aliases ENABLE ROW LEVEL SECURITY;

ALTER TABLE specs.product_specs ENABLE ROW LEVEL SECURITY;
ALTER TABLE specs.spec_network ENABLE ROW LEVEL SECURITY;
ALTER TABLE specs.spec_body ENABLE ROW LEVEL SECURITY;
ALTER TABLE specs.spec_display ENABLE ROW LEVEL SECURITY;
ALTER TABLE specs.spec_platform ENABLE ROW LEVEL SECURITY;
ALTER TABLE specs.spec_memory ENABLE ROW LEVEL SECURITY;
ALTER TABLE specs.spec_camera_main ENABLE ROW LEVEL SECURITY;
ALTER TABLE specs.spec_camera_selfie ENABLE ROW LEVEL SECURITY;
ALTER TABLE specs.spec_connectivity ENABLE ROW LEVEL SECURITY;
ALTER TABLE specs.spec_battery ENABLE ROW LEVEL SECURITY;

ALTER TABLE listings.market_listings ENABLE ROW LEVEL SECURITY;
ALTER TABLE listings.listing_prices ENABLE ROW LEVEL SECURITY;
ALTER TABLE listings.listing_network ENABLE ROW LEVEL SECURITY;
ALTER TABLE listings.listing_body ENABLE ROW LEVEL SECURITY;
ALTER TABLE listings.listing_display ENABLE ROW LEVEL SECURITY;
ALTER TABLE listings.listing_platform ENABLE ROW LEVEL SECURITY;
ALTER TABLE listings.listing_memory ENABLE ROW LEVEL SECURITY;
ALTER TABLE listings.listing_camera_main ENABLE ROW LEVEL SECURITY;
ALTER TABLE listings.listing_camera_selfie ENABLE ROW LEVEL SECURITY;
ALTER TABLE listings.listing_connectivity ENABLE ROW LEVEL SECURITY;
ALTER TABLE listings.listing_battery ENABLE ROW LEVEL SECURITY;

ALTER TABLE metadata.scrape_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE metadata.etl_rejects ENABLE ROW LEVEL SECURITY;
ALTER TABLE metadata.data_quality ENABLE ROW LEVEL SECURITY;

ALTER TABLE staging.raw_json_records ENABLE ROW LEVEL SECURITY;

-- -----------------------------------------------------------------------------
-- Public / Read-Only Policies (anon & authenticated roles)
-- -----------------------------------------------------------------------------

-- Catalog Policies (Read-Only for Public/Clients)
CREATE POLICY "Allow public read on companies" ON catalog.companies FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public read on products" ON catalog.products FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public read on product_aliases" ON catalog.product_aliases FOR SELECT TO anon, authenticated USING (true);

-- Specs Policies (Read-Only for Public/Clients)
CREATE POLICY "Allow public read on product_specs" ON specs.product_specs FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public read on spec_network" ON specs.spec_network FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public read on spec_body" ON specs.spec_body FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public read on spec_display" ON specs.spec_display FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public read on spec_platform" ON specs.spec_platform FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public read on spec_memory" ON specs.spec_memory FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public read on spec_camera_main" ON specs.spec_camera_main FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public read on spec_camera_selfie" ON specs.spec_camera_selfie FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public read on spec_connectivity" ON specs.spec_connectivity FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public read on spec_battery" ON specs.spec_battery FOR SELECT TO anon, authenticated USING (true);

-- Listings Policies (Read-Only for Public/Clients)
CREATE POLICY "Allow public read on market_listings" ON listings.market_listings FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public read on listing_prices" ON listings.listing_prices FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public read on listing_network" ON listings.listing_network FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public read on listing_body" ON listings.listing_body FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public read on listing_display" ON listings.listing_display FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public read on listing_platform" ON listings.listing_platform FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public read on listing_memory" ON listings.listing_memory FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public read on listing_camera_main" ON listings.listing_camera_main FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public read on listing_camera_selfie" ON listings.listing_camera_selfie FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public read on listing_connectivity" ON listings.listing_connectivity FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public read on listing_battery" ON listings.listing_battery FOR SELECT TO anon, authenticated USING (true);

-- Metadata & Data Quality (Read-Only for Public/Clients)
CREATE POLICY "Allow public read on data_quality" ON metadata.data_quality FOR SELECT TO anon, authenticated USING (true);

-- -----------------------------------------------------------------------------
-- Service Role / Admin Full Management Policies
-- (Allows ETL processes, background scripts, and Supabase service_role full CRUD)
-- -----------------------------------------------------------------------------

CREATE POLICY "Service role full access on companies" ON catalog.companies FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on products" ON catalog.products FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on product_aliases" ON catalog.product_aliases FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Service role full access on product_specs" ON specs.product_specs FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on spec_network" ON specs.spec_network FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on spec_body" ON specs.spec_body FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on spec_display" ON specs.spec_display FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on spec_platform" ON specs.spec_platform FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on spec_memory" ON specs.spec_memory FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on spec_camera_main" ON specs.spec_camera_main FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on spec_camera_selfie" ON specs.spec_camera_selfie FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on spec_connectivity" ON specs.spec_connectivity FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on spec_battery" ON specs.spec_battery FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Service role full access on market_listings" ON listings.market_listings FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on listing_prices" ON listings.listing_prices FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on listing_network" ON listings.listing_network FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on listing_body" ON listings.listing_body FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on listing_display" ON listings.listing_display FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on listing_platform" ON listings.listing_platform FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on listing_memory" ON listings.listing_memory FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on listing_camera_main" ON listings.listing_camera_main FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on listing_camera_selfie" ON listings.listing_camera_selfie FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on listing_connectivity" ON listings.listing_connectivity FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on listing_battery" ON listings.listing_battery FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Service role full access on scrape_runs" ON metadata.scrape_runs FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on etl_rejects" ON metadata.etl_rejects FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on data_quality" ON metadata.data_quality FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Service role full access on raw_json_records" ON staging.raw_json_records FOR ALL TO service_role USING (true) WITH CHECK (true);


-- =============================================================================
-- 7. PERMISSIONS & SCHEMA GRANTS
-- =============================================================================

GRANT USAGE ON SCHEMA catalog, specs, listings, metadata, staging, analytics, etl TO anon, authenticated, service_role;

GRANT SELECT ON ALL TABLES IN SCHEMA catalog, specs, listings, analytics TO anon, authenticated;
GRANT SELECT ON ALL TABLES IN SCHEMA metadata TO authenticated;

GRANT ALL ON ALL TABLES IN SCHEMA catalog, specs, listings, metadata, staging, analytics, etl TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA catalog, specs, listings, metadata, staging, analytics, etl TO service_role;
