#!/usr/bin/env python3
"""Convert template_v2 organised mobile JSON files into Supabase v3 CSV tables.

Input contract
--------------
The input is the output of ``filestorage/organise_with_llm.py`` and therefore
uses the organised/template_v2 shape.  By default records are read from:

    filestorage/mobiles_organised/<source-domain>/*.json

Output contract
---------------
The output hierarchy mirrors ``schema_supabase.sql`` exactly:

    filestorage/csvs/catalog/*.csv
    filestorage/csvs/specs/*.csv
    filestorage/csvs/listings/*.csv
    filestorage/csvs/metadata/*.csv
    filestorage/csvs/staging/*.csv
    filestorage/csvs/_manifest/*

GSMArena is treated as the canonical specification source and populates the
``specs`` tables.  Other sources populate ``listings``.  Every valid JSON file
also receives a row in ``staging.raw_json_records`` and a data-quality row.

The database uses BIGINT identity keys.  CSV conversion happens before a
PostgreSQL session exists, so this script generates deterministic positive
BIGINT IDs from stable natural keys (company slug, product slug, source URL,
etc.).  The schema uses ``GENERATED BY DEFAULT AS IDENTITY``, which permits
explicit values during bulk loading while preserving all foreign-key links.

Only Python's standard library is required.  The script is cross-platform and
works from Windows, Linux and WSL.
"""

from __future__ import annotations

import argparse
import csv
from contextlib import ExitStack
from dataclasses import dataclass
from datetime import datetime, timezone
import hashlib
import json
import logging
import os
from pathlib import Path
import re
import shutil
import sys
import unicodedata
from typing import Any, Iterable, Mapping, Sequence
from urllib.parse import urlparse, urlunparse


LOG = logging.getLogger("jsonToCsv")
PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT_DIR = PROJECT_ROOT / "filestorage" / "mobiles_organised"
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "filestorage" / "csvs"
DEFAULT_CANONICAL_SOURCE = "gsmarena.com"
DEFAULT_CURRENCY = "PKR"

MONTHS = {"JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"}
SPACE_RE = re.compile(r"\s+")
SLUG_RE = re.compile(r"[^a-z0-9]+")


# Exact column order from schema_supabase.sql v3.
TABLE_FIELDS: dict[str, list[str]] = {
    "catalog.companies": [
        "company_id", "company_name", "company_slug", "created_at",
    ],
    "catalog.products": [
        "product_id", "company_id", "mobile_name", "product_slug",
        "created_by_source", "created_at", "updated_at",
    ],
    "catalog.product_aliases": [
        "alias_id", "product_id", "alias_name", "alias_slug",
        "source_domain", "created_at",
    ],
    "specs.product_specs": [
        "product_id", "release_year", "release_month", "release_day",
        "announced_text", "status_text", "colors", "has_loudspeaker",
        "has_3_5mm_jack", "specs_source", "last_updated",
    ],
    "specs.spec_network": [
        "product_id", "supports_2g", "supports_3g", "supports_4g", "supports_5g",
    ],
    "specs.spec_body": [
        "product_id", "dim_length_mm", "dim_width_mm", "dim_depth_mm",
        "weight_grams", "build_materials", "has_normal_sim", "has_nano_sim",
        "has_esim", "ip_rating", "is_water_resistant", "is_dust_resistant",
    ],
    "specs.spec_display": [
        "product_id", "screen_technology", "refresh_rate_hz",
        "peak_brightness_nits", "resolution_width", "resolution_height",
        "aspect_ratio", "pixel_density_ppi", "screen_protection",
    ],
    "specs.spec_platform": [
        "product_id", "operating_system", "chipset_name", "chipset_node_nm",
        "cpu_description", "gpu_name",
    ],
    "specs.spec_memory": [
        "product_id", "card_slot", "storage_ram_variants", "technology",
    ],
    "specs.spec_camera_main": [
        "product_id", "sensor_specs", "photo_features", "video_modes",
    ],
    "specs.spec_camera_selfie": [
        "product_id", "sensor_specs", "video_modes",
    ],
    "specs.spec_connectivity": [
        "product_id", "wifi_standards", "bluetooth_version", "positioning_systems",
        "has_nfc", "has_infrared", "has_fm_radio", "has_usb_a", "has_usb_b",
        "has_micro_usb", "has_usb_c", "has_fp_rear", "has_fp_side",
        "has_fp_under_display",
    ],
    "specs.spec_battery": [
        "product_id", "capacity_mah", "has_wireless_charging", "charging_specs",
    ],
    "metadata.scrape_runs": [
        "run_id", "source_domain", "started_at", "finished_at",
        "records_processed", "records_succeeded", "records_failed", "run_status",
    ],
    "metadata.etl_rejects": [
        "reject_id", "scrape_run_id", "source_domain", "source_url", "source_file",
        "reject_reason", "reject_detail", "raw_payload", "rejected_at",
        "resolved_at", "resolution_detail",
    ],
    "metadata.data_quality": [
        "score_id", "product_id", "listing_id", "source_domain",
        "completeness_pct", "fields_populated", "fields_total", "scored_at",
    ],
    "listings.market_listings": [
        "listing_id", "product_id", "instance_number", "source_domain", "source_url",
        "listing_title", "announced_text", "status_text", "release_year",
        "release_month", "release_day", "colors", "has_loudspeaker",
        "has_3_5mm_jack", "raw_payload", "scrape_run_id", "scraped_at",
    ],
    "listings.listing_prices": [
        "price_entry_id", "listing_id", "currency_code", "amount", "price_index",
        "created_at",
    ],
    "listings.listing_network": [
        "listing_id", "supports_2g", "supports_3g", "supports_4g", "supports_5g",
    ],
    "listings.listing_body": [
        "listing_id", "dim_length_mm", "dim_width_mm", "dim_depth_mm",
        "weight_grams", "build_materials", "has_normal_sim", "has_nano_sim",
        "has_esim", "ip_rating", "is_water_resistant", "is_dust_resistant",
    ],
    "listings.listing_display": [
        "listing_id", "screen_technology", "refresh_rate_hz",
        "peak_brightness_nits", "resolution_width", "resolution_height",
        "aspect_ratio", "pixel_density_ppi", "screen_protection",
    ],
    "listings.listing_platform": [
        "listing_id", "operating_system", "chipset_name", "chipset_node_nm",
        "cpu_description", "gpu_name",
    ],
    "listings.listing_memory": [
        "listing_id", "card_slot", "storage_ram_variants", "technology",
    ],
    "listings.listing_camera_main": [
        "listing_id", "sensor_specs", "photo_features", "video_modes",
    ],
    "listings.listing_camera_selfie": [
        "listing_id", "sensor_specs", "video_modes",
    ],
    "listings.listing_connectivity": [
        "listing_id", "wifi_standards", "bluetooth_version", "positioning_systems",
        "has_nfc", "has_infrared", "has_fm_radio", "has_usb_a", "has_usb_b",
        "has_micro_usb", "has_usb_c", "has_fp_rear", "has_fp_side",
        "has_fp_under_display",
    ],
    "listings.listing_battery": [
        "listing_id", "capacity_mah", "has_wireless_charging", "charging_specs",
    ],
    "staging.raw_json_records": [
        "staging_id", "record_key", "source_domain", "source_file", "source_url",
        "payload", "ingested_at", "processed_at", "status",
    ],
}

IMPORT_ORDER = [
    "metadata.scrape_runs",
    "catalog.companies",
    "catalog.products",
    "catalog.product_aliases",
    "specs.product_specs",
    "specs.spec_network",
    "specs.spec_body",
    "specs.spec_display",
    "specs.spec_platform",
    "specs.spec_memory",
    "specs.spec_camera_main",
    "specs.spec_camera_selfie",
    "specs.spec_connectivity",
    "specs.spec_battery",
    "listings.market_listings",
    "listings.listing_prices",
    "listings.listing_network",
    "listings.listing_body",
    "listings.listing_display",
    "listings.listing_platform",
    "listings.listing_memory",
    "listings.listing_camera_main",
    "listings.listing_camera_selfie",
    "listings.listing_connectivity",
    "listings.listing_battery",
    "metadata.data_quality",
    "metadata.etl_rejects",
    "staging.raw_json_records",
]

MANIFEST_FIELDS = [
    "record_key", "source_domain", "source_file", "source_url", "company_name",
    "mobile_name", "company_slug", "product_slug", "product_id", "listing_id",
    "is_canonical", "completeness_pct", "file_sha256",
]
ERROR_FIELDS = [
    "source_domain", "source_file", "source_url", "error_code", "error_message",
]


class ConversionError(ValueError):
    def __init__(self, code: str, message: str) -> None:
        super().__init__(message)
        self.code = code


@dataclass
class PhoneRecord:
    path: Path
    source_file: str
    source_domain: str
    source_url: str
    payload: dict[str, Any]
    raw_bytes: bytes
    file_sha256: str
    company_name: str
    mobile_name: str
    company_identity: str
    product_identity: str
    company_slug: str = ""
    product_slug: str = ""
    company_id: int = 0
    product_id: int = 0
    listing_id: int | None = None
    instance_number: int | None = None
    completeness_populated: int = 0
    completeness_total: int = 0

    @property
    def record_key(self) -> str:
        return hashlib.sha256(
            f"{self.source_domain}\0{self.source_url}".encode("utf-8")
        ).hexdigest()

    @property
    def completeness_pct(self) -> float:
        if not self.completeness_total:
            return 0.0
        return round(100.0 * self.completeness_populated / self.completeness_total, 2)

    @property
    def is_canonical(self) -> bool:
        return self.source_domain == DEFAULT_CANONICAL_SOURCE


@dataclass
class RejectRecord:
    source_domain: str
    source_file: str
    source_url: str
    code: str
    message: str
    payload: dict[str, Any] | None = None


# -----------------------------------------------------------------------------
# Generic conversion helpers
# -----------------------------------------------------------------------------

def canonical_site(value: str) -> str:
    host = str(value).strip().lower().split("@")[-1].split(":")[0]
    return re.sub(r"^www\.", "", host)


def canonicalize_url(value: Any, expected_site: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ConversionError("MISSING_URL", "URL is required in organised template_v2 JSON")
    parsed = urlparse(value.strip())
    if parsed.scheme.lower() not in {"http", "https"} or not parsed.netloc:
        raise ConversionError("INVALID_URL", f"Not a valid HTTP(S) URL: {value!r}")
    actual_site = canonical_site(parsed.netloc)
    if expected_site and actual_site != expected_site:
        raise ConversionError(
            "WRONG_URL_SITE",
            f"URL domain {actual_site!r} does not match source folder {expected_site!r}",
        )
    host = parsed.netloc.lower()
    return urlunparse(("https", host, parsed.path, "", parsed.query, ""))


def clean_text(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, (dict, list)):
        return compact_json(value)
    return SPACE_RE.sub(" ", str(value)).strip()


def required_text(value: Any, field: str) -> str:
    text = clean_text(value)
    if not text:
        raise ConversionError("MISSING_FIELD", f"{field} is required")
    return text


def compact_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"), sort_keys=True)


def section(payload: Mapping[str, Any], name: str) -> Mapping[str, Any]:
    value = payload.get(name)
    return value if isinstance(value, Mapping) else {}


def nested_section(payload: Mapping[str, Any], first: str, second: str) -> Mapping[str, Any]:
    parent = section(payload, first)
    value = parent.get(second)
    return value if isinstance(value, Mapping) else {}


def as_list(value: Any) -> list[Any]:
    if value is None:
        return []
    return value if isinstance(value, list) else [value]


def bool_value(value: Any, default: bool = False) -> bool:
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return value != 0
    text = str(value).strip().lower()
    if text in {"1", "true", "t", "yes", "y", "on", "supported"}:
        return True
    if text in {"0", "false", "f", "no", "n", "off", "none", "unsupported"}:
        return False
    return default


def bool_csv(value: Any, default: bool = False) -> str:
    return "true" if bool_value(value, default) else "false"


def number_value(value: Any, default: int | float = 0) -> int | float:
    if value is None or isinstance(value, bool):
        return default
    if isinstance(value, (int, float)):
        return value
    text = str(value).strip().replace(",", "")
    try:
        result = float(text)
    except ValueError:
        match = re.search(r"[-+]?\d+(?:\.\d+)?", text)
        if not match:
            return default
        result = float(match.group(0))
    return int(result) if result.is_integer() else result


def optional_number(value: Any) -> str | int | float:
    if value is None or value == "":
        return ""
    result = number_value(value, 0)
    return result


def int_value(value: Any, default: int = 0) -> int:
    return int(round(float(number_value(value, default))))


def release_values(payload: Mapping[str, Any]) -> tuple[int, str, str | int]:
    year = int_value(payload.get("Year"), 2014)
    if year < 1900 or year > 2200:
        year = 2014
    month = clean_text(payload.get("Month")).upper() or "DEC"
    if month not in MONTHS:
        month = "DEC"
    day_raw = payload.get("Day")
    if day_raw is None or day_raw == "":
        day: str | int = ""
    else:
        candidate = int_value(day_raw, 0)
        day = candidate if 1 <= candidate <= 31 else ""
    return year, month, day


def pg_text_array(value: Any) -> str:
    """Encode a Python list as a PostgreSQL TEXT[] array literal."""
    items = []
    for item in as_list(value):
        if item is None:
            continue
        text = clean_text(item)
        if not text:
            continue
        text = text.replace("\\", "\\\\").replace('"', '\\"')
        items.append(f'"{text}"')
    return "{" + ",".join(items) + "}"


def json_array(value: Any, fallback: list[Any] | None = None) -> str:
    items = value if isinstance(value, list) else (fallback if fallback is not None else [])
    return compact_json(items)


def normalize_space_casefold(value: str) -> str:
    return SPACE_RE.sub(" ", value).strip().casefold()


def slugify(value: str) -> str:
    normalized = unicodedata.normalize("NFKD", value)
    ascii_text = normalized.encode("ascii", "ignore").decode("ascii").lower()
    slug = SLUG_RE.sub("-", ascii_text).strip("-")
    if slug:
        return slug
    return "item-" + hashlib.sha256(value.encode("utf-8")).hexdigest()[:12]


def stable_bigint(namespace: str, key: str) -> int:
    """Stable positive 63-bit integer suitable for PostgreSQL BIGINT."""
    digest = hashlib.sha256(f"{namespace}\0{key}".encode("utf-8")).digest()
    value = int.from_bytes(digest[:8], "big") & ((1 << 63) - 1)
    return value or 1


def file_sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def display_name(company: str, mobile: str) -> str:
    if normalize_space_casefold(mobile).startswith(normalize_space_casefold(company) + " "):
        return mobile
    return f"{company} {mobile}".strip()


def positive_prices(value: Any) -> list[int | float]:
    result: list[int | float] = []
    for item in as_list(value):
        if isinstance(item, bool):
            continue
        parsed = number_value(item, -1)
        if float(parsed) > 0:
            result.append(parsed)
    return result


QUALITY_PATHS: tuple[tuple[str, ...], ...] = (
    ("CompanyName",), ("MobileName",), ("URL",),
    ("Network", "2G"), ("Network", "3G"), ("Network", "4G"), ("Network", "5G"),
    ("Announced",), ("Status",), ("Year",), ("Month",), ("Day",),
    ("Body", "Dimensions", "DimensionA"), ("Body", "Dimensions", "DimensionB"),
    ("Body", "Dimensions", "DimensionC"), ("Body", "Weight"), ("Body", "Build"),
    ("Body", "Normal-SIM"), ("Body", "Nano-SIM"), ("Body", "E-SIM"),
    ("Body", "Resistance-Standard"), ("Body", "Resistance-Water"),
    ("Body", "Resistance-Dust"),
    ("Display", "Screen"), ("Display", "Refresh-Rate"), ("Display", "Brightness"),
    ("Display", "ResolutionA"), ("Display", "ResolutionB"), ("Display", "Ratio"),
    ("Display", "Pixel-Density"), ("Display", "Protection"),
    ("Platform", "OS"), ("Platform", "Chipset"), ("Platform", "Chipset-Size"),
    ("Platform", "CPU"), ("Platform", "GPU"),
    ("Memory", "Card slot"), ("Memory", "Types"), ("Memory", "Technology"),
    ("Main Camera", "Specifications"), ("Main Camera", "Features"),
    ("Main Camera", "Video"), ("Selfie Camera", "Specifications"),
    ("Selfie Camera", "Video"),
    ("Sound", "Loudspeaker"), ("Sound", "3.5mm jack"),
    ("Features", "WLAN"), ("Features", "Bluetooth"), ("Features", "Positioning"),
    ("Features", "NFC"), ("Features", "Infrared port"), ("Features", "Radio"),
    ("Features", "USB-A"), ("Features", "USB-B"), ("Features", "Micro-USB"),
    ("Features", "USB-C"), ("Features", "BackFingerPrint"),
    ("Features", "SideFingerPrint"), ("Features", "InDisplayFingerPrint"),
    ("Battery", "Capacity"), ("Battery", "WirelessCharging"),
    ("Battery", "Charging"), ("Colors",), ("Price",),
)


def path_value(payload: Mapping[str, Any], path: Sequence[str]) -> Any:
    current: Any = payload
    for key in path:
        if not isinstance(current, Mapping) or key not in current:
            return None
        current = current[key]
    return current


def has_semantic_value(value: Any) -> bool:
    if value is None:
        return False
    if isinstance(value, str):
        return bool(value.strip())
    if isinstance(value, (list, dict)):
        return bool(value)
    return True


def quality_counts(payload: Mapping[str, Any]) -> tuple[int, int]:
    populated = sum(has_semantic_value(path_value(payload, path)) for path in QUALITY_PATHS)
    return populated, len(QUALITY_PATHS)


# -----------------------------------------------------------------------------
# Input discovery and identity assignment
# -----------------------------------------------------------------------------

def load_phone_json(path: Path, input_dir: Path) -> PhoneRecord:
    source_domain = canonical_site(path.parent.name)
    source_file = path.relative_to(input_dir).as_posix()
    try:
        raw = path.read_bytes()
        payload = json.loads(raw.decode("utf-8-sig"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise ConversionError("INVALID_JSON", f"{source_file}: {exc}") from exc
    if not isinstance(payload, dict):
        raise ConversionError("INVALID_PAYLOAD", f"{source_file}: top-level JSON must be an object")

    company = required_text(payload.get("CompanyName"), "CompanyName")
    mobile = required_text(payload.get("MobileName"), "MobileName")
    url = canonicalize_url(payload.get("URL"), source_domain)
    populated, total = quality_counts(payload)
    return PhoneRecord(
        path=path,
        source_file=source_file,
        source_domain=source_domain,
        source_url=url,
        payload=payload,
        raw_bytes=raw,
        file_sha256=file_sha256(raw),
        company_name=company,
        mobile_name=mobile,
        company_identity=normalize_space_casefold(company),
        product_identity=f"{normalize_space_casefold(company)}\0{normalize_space_casefold(mobile)}",
        completeness_populated=populated,
        completeness_total=total,
    )


def discover_paths(input_dir: Path, selected_sites: set[str] | None) -> list[Path]:
    if not input_dir.is_dir():
        raise FileNotFoundError(f"Input directory does not exist: {input_dir}")
    paths: list[Path] = []
    for site_dir in sorted(p for p in input_dir.iterdir() if p.is_dir()):
        site = canonical_site(site_dir.name)
        if selected_sites is not None and site not in selected_sites:
            continue
        for path in sorted(site_dir.glob("*.json")):
            if not path.name.startswith("_"):
                paths.append(path)
    return paths


def assign_identity_slugs(records: list[PhoneRecord]) -> None:
    company_names: dict[str, str] = {}
    for record in records:
        existing = company_names.get(record.company_identity)
        if existing is None or record.company_name < existing:
            company_names[record.company_identity] = record.company_name

    company_base_groups: dict[str, list[str]] = {}
    for identity, name in company_names.items():
        company_base_groups.setdefault(slugify(name), []).append(identity)

    company_slug_by_identity: dict[str, str] = {}
    for base, identities in company_base_groups.items():
        for identity in sorted(identities):
            company_slug_by_identity[identity] = (
                base if len(identities) == 1
                else f"{base}-{hashlib.sha256(identity.encode()).hexdigest()[:8]}"
            )

    product_groups: dict[str, list[str]] = {}
    product_base_by_identity: dict[str, str] = {}
    for record in records:
        company_slug = company_slug_by_identity[record.company_identity]
        base = f"{company_slug}-{slugify(record.mobile_name)}"
        product_base_by_identity[record.product_identity] = base
        product_groups.setdefault(base, []).append(record.product_identity)

    product_slug_by_identity: dict[str, str] = {}
    for base, identities_raw in product_groups.items():
        identities = sorted(set(identities_raw))
        for identity in identities:
            product_slug_by_identity[identity] = (
                base if len(identities) == 1
                else f"{base}-{hashlib.sha256(identity.encode()).hexdigest()[:8]}"
            )

    seen_ids: dict[int, tuple[str, str]] = {}
    for record in records:
        record.company_slug = company_slug_by_identity[record.company_identity]
        record.product_slug = product_slug_by_identity[record.product_identity]
        record.company_id = stable_bigint("company", record.company_slug)
        record.product_id = stable_bigint("product", record.product_slug)
        for namespace, value, key in (
            ("company", record.company_id, record.company_slug),
            ("product", record.product_id, record.product_slug),
        ):
            previous = seen_ids.get(value)
            marker = (namespace, key)
            if previous is not None and previous != marker:
                raise RuntimeError(f"Stable BIGINT collision between {previous!r} and {marker!r}")
            seen_ids[value] = marker


def assign_listings(records: list[PhoneRecord], canonical_source: str) -> None:
    groups: dict[tuple[int, str], list[PhoneRecord]] = {}
    seen_urls: dict[str, PhoneRecord] = {}
    for record in records:
        if record.source_domain == canonical_source:
            continue
        if record.source_url in seen_urls:
            other = seen_urls[record.source_url]
            raise ConversionError(
                "DUPLICATE_URL",
                f"Duplicate listing URL in {other.source_file} and {record.source_file}: {record.source_url}",
            )
        seen_urls[record.source_url] = record
        record.listing_id = stable_bigint("listing", record.source_url)
        groups.setdefault((record.product_id, record.source_domain), []).append(record)

    for group_records in groups.values():
        for index, record in enumerate(sorted(group_records, key=lambda r: (r.source_url, r.source_file)), start=1):
            record.instance_number = index


# -----------------------------------------------------------------------------
# CSV row construction
# -----------------------------------------------------------------------------

def common_sections(record: PhoneRecord) -> dict[str, Mapping[str, Any]]:
    p = record.payload
    return {
        "network": section(p, "Network"),
        "body": section(p, "Body"),
        "dimensions": nested_section(p, "Body", "Dimensions"),
        "display": section(p, "Display"),
        "platform": section(p, "Platform"),
        "memory": section(p, "Memory"),
        "main": section(p, "Main Camera"),
        "selfie": section(p, "Selfie Camera"),
        "sound": section(p, "Sound"),
        "features": section(p, "Features"),
        "battery": section(p, "Battery"),
    }


def shared_spec_values(record: PhoneRecord) -> dict[str, dict[str, Any]]:
    s = common_sections(record)
    p = record.payload
    year, month, day = release_values(p)
    network, body, dims = s["network"], s["body"], s["dimensions"]
    display, platform, memory = s["display"], s["platform"], s["memory"]
    main, selfie, sound = s["main"], s["selfie"], s["sound"]
    features, battery = s["features"], s["battery"]

    return {
        "header": {
            "release_year": year,
            "release_month": month,
            "release_day": day,
            "announced_text": clean_text(p.get("Announced")),
            "status_text": clean_text(p.get("Status")),
            "colors": pg_text_array(p.get("Colors")),
            "has_loudspeaker": bool_csv(sound.get("Loudspeaker"), True),
            "has_3_5mm_jack": bool_csv(sound.get("3.5mm jack"), True),
        },
        "network": {
            "supports_2g": bool_csv(network.get("2G"), True),
            "supports_3g": bool_csv(network.get("3G"), True),
            "supports_4g": bool_csv(network.get("4G"), False),
            "supports_5g": bool_csv(network.get("5G"), False),
        },
        "body": {
            "dim_length_mm": number_value(dims.get("DimensionA"), 50.0),
            "dim_width_mm": number_value(dims.get("DimensionB"), 50.0),
            "dim_depth_mm": number_value(dims.get("DimensionC"), 5.0),
            "weight_grams": number_value(body.get("Weight"), 25.0),
            "build_materials": clean_text(body.get("Build")),
            "has_normal_sim": bool_csv(body.get("Normal-SIM"), False),
            "has_nano_sim": bool_csv(body.get("Nano-SIM"), True),
            "has_esim": bool_csv(body.get("E-SIM"), False),
            "ip_rating": clean_text(body.get("Resistance-Standard")),
            "is_water_resistant": bool_csv(body.get("Resistance-Water"), False),
            "is_dust_resistant": bool_csv(body.get("Resistance-Dust"), True),
        },
        "display": {
            "screen_technology": clean_text(display.get("Screen")) or "LCD",
            "refresh_rate_hz": int_value(display.get("Refresh-Rate"), 60),
            "peak_brightness_nits": int_value(display.get("Brightness"), 60),
            "resolution_width": int_value(display.get("ResolutionA"), 240),
            "resolution_height": int_value(display.get("ResolutionB"), 240),
            "aspect_ratio": clean_text(display.get("Ratio")),
            "pixel_density_ppi": optional_number(display.get("Pixel-Density")),
            "screen_protection": clean_text(display.get("Protection")),
        },
        "platform": {
            "operating_system": clean_text(platform.get("OS")),
            "chipset_name": clean_text(platform.get("Chipset")),
            "chipset_node_nm": optional_number(platform.get("Chipset-Size")),
            "cpu_description": clean_text(platform.get("CPU")),
            "gpu_name": clean_text(platform.get("GPU")),
        },
        "memory": {
            "card_slot": clean_text(memory.get("Card slot")),
            "storage_ram_variants": json_array(memory.get("Types"), [[0, 0]]),
            "technology": clean_text(memory.get("Technology")),
        },
        "camera_main": {
            "sensor_specs": pg_text_array(main.get("Specifications")),
            "photo_features": clean_text(main.get("Features")),
            "video_modes": pg_text_array(main.get("Video")),
        },
        "camera_selfie": {
            "sensor_specs": pg_text_array(selfie.get("Specifications")),
            "video_modes": pg_text_array(selfie.get("Video")),
        },
        "connectivity": {
            "wifi_standards": clean_text(features.get("WLAN")),
            "bluetooth_version": clean_text(features.get("Bluetooth")),
            "positioning_systems": clean_text(features.get("Positioning")),
            "has_nfc": bool_csv(features.get("NFC"), False),
            "has_infrared": bool_csv(features.get("Infrared port"), False),
            "has_fm_radio": bool_csv(features.get("Radio"), True),
            "has_usb_a": bool_csv(features.get("USB-A"), False),
            "has_usb_b": bool_csv(features.get("USB-B"), False),
            "has_micro_usb": bool_csv(features.get("Micro-USB"), True),
            "has_usb_c": bool_csv(features.get("USB-C"), False),
            "has_fp_rear": bool_csv(features.get("BackFingerPrint"), False),
            "has_fp_side": bool_csv(features.get("SideFingerPrint"), False),
            "has_fp_under_display": bool_csv(features.get("InDisplayFingerPrint"), False),
        },
        "battery": {
            "capacity_mah": int_value(battery.get("Capacity"), 0),
            "has_wireless_charging": bool_csv(battery.get("WirelessCharging"), False),
            "charging_specs": pg_text_array(battery.get("Charging")),
        },
    }


def canonical_rows(record: PhoneRecord, generated_at: str, canonical_source: str) -> dict[str, dict[str, Any]]:
    values = shared_spec_values(record)
    pid = record.product_id
    return {
        "specs.product_specs": {
            "product_id": pid,
            **values["header"],
            "specs_source": canonical_source,
            "last_updated": generated_at,
        },
        "specs.spec_network": {"product_id": pid, **values["network"]},
        "specs.spec_body": {"product_id": pid, **values["body"]},
        "specs.spec_display": {"product_id": pid, **values["display"]},
        "specs.spec_platform": {"product_id": pid, **values["platform"]},
        "specs.spec_memory": {"product_id": pid, **values["memory"]},
        "specs.spec_camera_main": {"product_id": pid, **values["camera_main"]},
        "specs.spec_camera_selfie": {"product_id": pid, **values["camera_selfie"]},
        "specs.spec_connectivity": {"product_id": pid, **values["connectivity"]},
        "specs.spec_battery": {"product_id": pid, **values["battery"]},
    }


def listing_rows(
    record: PhoneRecord,
    generated_at: str,
    run_id: int,
    currency: str,
) -> dict[str, list[dict[str, Any]]]:
    if record.listing_id is None or record.instance_number is None:
        raise RuntimeError(f"Listing identity was not assigned for {record.source_file}")
    values = shared_spec_values(record)
    lid = record.listing_id
    header = values["header"]
    rows: dict[str, list[dict[str, Any]]] = {
        "listings.market_listings": [{
            "listing_id": lid,
            "product_id": record.product_id,
            "instance_number": record.instance_number,
            "source_domain": record.source_domain,
            "source_url": record.source_url,
            "listing_title": display_name(record.company_name, record.mobile_name),
            "announced_text": header["announced_text"],
            "status_text": header["status_text"],
            "release_year": header["release_year"],
            "release_month": header["release_month"],
            "release_day": header["release_day"],
            "colors": header["colors"],
            "has_loudspeaker": header["has_loudspeaker"],
            "has_3_5mm_jack": header["has_3_5mm_jack"],
            "raw_payload": compact_json(record.payload),
            "scrape_run_id": run_id,
            "scraped_at": generated_at,
        }],
        "listings.listing_network": [{"listing_id": lid, **values["network"]}],
        "listings.listing_body": [{"listing_id": lid, **values["body"]}],
        "listings.listing_display": [{"listing_id": lid, **values["display"]}],
        "listings.listing_platform": [{"listing_id": lid, **values["platform"]}],
        "listings.listing_memory": [{"listing_id": lid, **values["memory"]}],
        "listings.listing_camera_main": [{"listing_id": lid, **values["camera_main"]}],
        "listings.listing_camera_selfie": [{"listing_id": lid, **values["camera_selfie"]}],
        "listings.listing_connectivity": [{"listing_id": lid, **values["connectivity"]}],
        "listings.listing_battery": [{"listing_id": lid, **values["battery"]}],
        "listings.listing_prices": [],
    }
    for index, amount in enumerate(positive_prices(record.payload.get("Price"))):
        rows["listings.listing_prices"].append({
            "price_entry_id": stable_bigint("price", f"{lid}\0{currency}\0{index}"),
            "listing_id": lid,
            "currency_code": currency,
            "amount": amount,
            "price_index": index,
            "created_at": generated_at,
        })
    return rows


# -----------------------------------------------------------------------------
# Output tree
# -----------------------------------------------------------------------------

class CsvTree:
    def __init__(self, root: Path) -> None:
        self.root = root
        self.stack = ExitStack()
        self.writers: dict[str, csv.DictWriter] = {}
        self.files: list[str] = []

    def __enter__(self) -> "CsvTree":
        self.root.mkdir(parents=True, exist_ok=True)
        for table, fields in TABLE_FIELDS.items():
            schema, name = table.split(".", 1)
            self._open(table, self.root / schema / f"{name}.csv", fields)
        self._open("_manifest.records", self.root / "_manifest" / "records.csv", MANIFEST_FIELDS)
        self._open("_manifest.errors", self.root / "_manifest" / "errors.csv", ERROR_FIELDS)
        return self

    def _open(self, key: str, path: Path, fields: Sequence[str]) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        handle = self.stack.enter_context(path.open("w", encoding="utf-8", newline=""))
        writer = csv.DictWriter(handle, fieldnames=list(fields), extrasaction="raise")
        writer.writeheader()
        self.writers[key] = writer
        self.files.append(path.relative_to(self.root).as_posix())

    def write(self, table: str, row: Mapping[str, Any]) -> None:
        self.writers[table].writerow(row)

    def write_many(self, table: str, rows: Iterable[Mapping[str, Any]]) -> None:
        for row in rows:
            self.write(table, row)

    def __exit__(self, exc_type: Any, exc: Any, traceback: Any) -> bool:
        self.stack.close()
        return False


def replace_output_tree(temp_root: Path, output_dir: Path) -> None:
    if output_dir.exists():
        shutil.rmtree(output_dir)
    os.replace(temp_root, output_dir)


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2, sort_keys=True)
        handle.write("\n")


# -----------------------------------------------------------------------------
# Main conversion
# -----------------------------------------------------------------------------

def run_conversion(args: argparse.Namespace) -> dict[str, Any]:
    input_dir = args.input_dir.resolve()
    output_dir = args.output_dir.resolve()
    canonical_source = canonical_site(args.canonical_source)
    currency = args.currency.strip().upper()
    if not re.fullmatch(r"[A-Z]{3}", currency):
        raise ValueError("--currency must be a three-letter ISO-style code such as PKR or USD")

    selected_sites = {canonical_site(x) for x in args.site} if args.site else None
    paths = discover_paths(input_dir, selected_sites)
    generated_at = datetime.now(timezone.utc).isoformat(timespec="seconds")

    records: list[PhoneRecord] = []
    rejects: list[RejectRecord] = []
    discovered_by_source: dict[str, int] = {}
    success_by_source: dict[str, int] = {}
    failure_by_source: dict[str, int] = {}

    for index, path in enumerate(paths, start=1):
        site = canonical_site(path.parent.name)
        relative = path.relative_to(input_dir).as_posix()
        discovered_by_source[site] = discovered_by_source.get(site, 0) + 1
        try:
            record = load_phone_json(path, input_dir)
            records.append(record)
            success_by_source[site] = success_by_source.get(site, 0) + 1
        except ConversionError as exc:
            failure_by_source[site] = failure_by_source.get(site, 0) + 1
            rejects.append(RejectRecord(site, relative, "", exc.code, str(exc)))
            LOG.error("%s: %s", relative, exc)
            if args.strict:
                raise
        if index % 1000 == 0:
            LOG.info("Validated %d/%d JSON files", index, len(paths))

    assign_identity_slugs(records)

    # Duplicate source URLs are invalid because listings.market_listings.source_url is UNIQUE
    # and staging lineage must remain one-record-per-source-page.
    seen_source_urls: dict[tuple[str, str], PhoneRecord] = {}
    deduped: list[PhoneRecord] = []
    for record in sorted(records, key=lambda r: (r.source_domain, r.source_url, r.source_file)):
        marker = (record.source_domain, record.source_url)
        if marker in seen_source_urls:
            first = seen_source_urls[marker]
            failure_by_source[record.source_domain] = failure_by_source.get(record.source_domain, 0) + 1
            success_by_source[record.source_domain] = max(0, success_by_source.get(record.source_domain, 0) - 1)
            rejects.append(RejectRecord(
                record.source_domain,
                record.source_file,
                record.source_url,
                "DUPLICATE_URL",
                f"Duplicate URL; first accepted from {first.source_file}",
                record.payload,
            ))
            if args.strict:
                raise ConversionError("DUPLICATE_URL", rejects[-1].message)
            continue
        seen_source_urls[marker] = record
        deduped.append(record)
    records = deduped

    assign_listings(records, canonical_source)

    # One canonical specs row per product.  If duplicate canonical records exist,
    # retain the most complete one, then the lexicographically first source file.
    canonical_candidates: dict[int, list[PhoneRecord]] = {}
    for record in records:
        if record.source_domain == canonical_source:
            canonical_candidates.setdefault(record.product_id, []).append(record)
    canonical_record_by_product: dict[int, PhoneRecord] = {}
    for product_id, candidates in canonical_candidates.items():
        canonical_record_by_product[product_id] = sorted(
            candidates,
            key=lambda r: (-r.completeness_pct, r.source_file),
        )[0]

    # Deterministic source run IDs are shared by listings/rejects.
    sources = sorted(set(discovered_by_source) | {r.source_domain for r in records})
    run_id_by_source = {source: stable_bigint("scrape_run", source) for source in sources}

    temp_root = output_dir.with_name(f".{output_dir.name}.build.{os.getpid()}")
    if temp_root.exists():
        shutil.rmtree(temp_root)

    counts: dict[str, int] = {table: 0 for table in TABLE_FIELDS}
    manifest_record_count = 0
    try:
        with CsvTree(temp_root) as out:
            # metadata.scrape_runs
            for source in sources:
                processed = discovered_by_source.get(source, 0)
                failed = failure_by_source.get(source, 0)
                succeeded = success_by_source.get(source, 0)
                out.write("metadata.scrape_runs", {
                    "run_id": run_id_by_source[source],
                    "source_domain": source,
                    "started_at": generated_at,
                    "finished_at": generated_at,
                    "records_processed": processed,
                    "records_succeeded": succeeded,
                    "records_failed": failed,
                    "run_status": "completed" if failed == 0 else "completed_with_errors",
                })
                counts["metadata.scrape_runs"] += 1

            # Catalog companies.
            company_rows: dict[int, dict[str, Any]] = {}
            for record in records:
                company_rows.setdefault(record.company_id, {
                    "company_id": record.company_id,
                    "company_name": record.company_name,
                    "company_slug": record.company_slug,
                    "created_at": generated_at,
                })
            for row in sorted(company_rows.values(), key=lambda r: str(r["company_slug"])):
                out.write("catalog.companies", row)
                counts["catalog.companies"] += 1

            # Catalog products.
            product_groups: dict[int, list[PhoneRecord]] = {}
            for record in records:
                product_groups.setdefault(record.product_id, []).append(record)
            for product_id, group in sorted(product_groups.items(), key=lambda item: item[1][0].product_slug):
                representative = sorted(
                    group,
                    key=lambda r: (r.source_domain != canonical_source, -r.completeness_pct, r.source_file),
                )[0]
                sources_for_product = sorted({r.source_domain for r in group})
                created_by = canonical_source if canonical_source in sources_for_product else sources_for_product[0]
                out.write("catalog.products", {
                    "product_id": product_id,
                    "company_id": representative.company_id,
                    "mobile_name": representative.mobile_name,
                    "product_slug": representative.product_slug,
                    "created_by_source": created_by,
                    "created_at": generated_at,
                    "updated_at": generated_at,
                })
                counts["catalog.products"] += 1

            # product_aliases: emit only genuine alternative cleaned identities that map
            # to the same product.  With template_v2 this is normally empty, which is
            # preferable to manufacturing aliases that were not observed.
            alias_rows: dict[str, dict[str, Any]] = {}
            for product_id, group in product_groups.items():
                canonical = sorted(group, key=lambda r: (r.source_domain != canonical_source, r.source_file))[0]
                canonical_full = display_name(canonical.company_name, canonical.mobile_name)
                canonical_alias_slug = slugify(canonical_full)
                for record in group:
                    alias_name = display_name(record.company_name, record.mobile_name)
                    alias_slug = slugify(alias_name)
                    if alias_slug == canonical_alias_slug:
                        continue
                    alias_rows.setdefault(alias_slug, {
                        "alias_id": stable_bigint("alias", alias_slug),
                        "product_id": product_id,
                        "alias_name": alias_name,
                        "alias_slug": alias_slug,
                        "source_domain": record.source_domain,
                        "created_at": generated_at,
                    })
            for row in sorted(alias_rows.values(), key=lambda r: str(r["alias_slug"])):
                out.write("catalog.product_aliases", row)
                counts["catalog.product_aliases"] += 1

            # Canonical GSMArena specification tables.
            for product_id, record in sorted(canonical_record_by_product.items(), key=lambda item: item[1].product_slug):
                for table, row in canonical_rows(record, generated_at, canonical_source).items():
                    out.write(table, row)
                    counts[table] += 1

            # Marketplace listing tables and structured prices.
            for record in sorted(
                (r for r in records if r.source_domain != canonical_source),
                key=lambda r: (r.source_domain, r.product_slug, r.instance_number or 0, r.source_url),
            ):
                rows_by_table = listing_rows(
                    record,
                    generated_at,
                    run_id_by_source[record.source_domain],
                    currency,
                )
                for table, rows in rows_by_table.items():
                    out.write_many(table, rows)
                    counts[table] += len(rows)

            # Staging, data quality and manifest inventory for every accepted JSON.
            for record in sorted(records, key=lambda r: (r.source_domain, r.source_file)):
                staging_id = stable_bigint("staging", f"{record.source_domain}\0{record.source_file}")
                out.write("staging.raw_json_records", {
                    "staging_id": staging_id,
                    "record_key": record.record_key,
                    "source_domain": record.source_domain,
                    "source_file": record.source_file,
                    "source_url": record.source_url,
                    "payload": compact_json(record.payload),
                    "ingested_at": generated_at,
                    "processed_at": generated_at,
                    "status": "processed",
                })
                counts["staging.raw_json_records"] += 1

                quality_target = (
                    f"product:{record.product_id}"
                    if record.source_domain == canonical_source
                    else f"listing:{record.listing_id}"
                )
                out.write("metadata.data_quality", {
                    "score_id": stable_bigint("quality", f"{record.source_domain}\0{quality_target}\0{record.source_file}"),
                    "product_id": record.product_id,
                    "listing_id": "" if record.source_domain == canonical_source else record.listing_id,
                    "source_domain": record.source_domain,
                    "completeness_pct": f"{record.completeness_pct:.2f}",
                    "fields_populated": record.completeness_populated,
                    "fields_total": record.completeness_total,
                    "scored_at": generated_at,
                })
                counts["metadata.data_quality"] += 1

                out.write("_manifest.records", {
                    "record_key": record.record_key,
                    "source_domain": record.source_domain,
                    "source_file": record.source_file,
                    "source_url": record.source_url,
                    "company_name": record.company_name,
                    "mobile_name": record.mobile_name,
                    "company_slug": record.company_slug,
                    "product_slug": record.product_slug,
                    "product_id": record.product_id,
                    "listing_id": record.listing_id or "",
                    "is_canonical": "true" if record.source_domain == canonical_source else "false",
                    "completeness_pct": f"{record.completeness_pct:.2f}",
                    "file_sha256": record.file_sha256,
                })
                manifest_record_count += 1

            # Rejects are represented in both metadata.etl_rejects and manifest errors.
            for reject in rejects:
                run_id = run_id_by_source.get(reject.source_domain)
                reject_key = f"{reject.source_domain}\0{reject.source_file}\0{reject.code}"
                out.write("metadata.etl_rejects", {
                    "reject_id": stable_bigint("reject", reject_key),
                    "scrape_run_id": run_id or "",
                    "source_domain": reject.source_domain,
                    "source_url": reject.source_url,
                    "source_file": reject.source_file,
                    "reject_reason": reject.code,
                    "reject_detail": reject.message,
                    "raw_payload": compact_json(reject.payload) if reject.payload is not None else "",
                    "rejected_at": generated_at,
                    "resolved_at": "",
                    "resolution_detail": "",
                })
                counts["metadata.etl_rejects"] += 1
                out.write("_manifest.errors", {
                    "source_domain": reject.source_domain,
                    "source_file": reject.source_file,
                    "source_url": reject.source_url,
                    "error_code": reject.code,
                    "error_message": reject.message,
                })

        manifest = {
            "format_version": 3,
            "generated_at": generated_at,
            "input_contract": "filestorage/template_v2.json / organised JSON",
            "database_contract": "schema_supabase.sql v3",
            "input_directory": str(input_dir),
            "output_directory": str(output_dir),
            "canonical_source": canonical_source,
            "default_price_currency": currency,
            "records_discovered": len(paths),
            "records_written": len(records),
            "records_rejected": len(rejects),
            "canonical_records_selected": len(canonical_record_by_product),
            "marketplace_listings": sum(1 for r in records if r.source_domain != canonical_source),
            "companies": counts["catalog.companies"],
            "products": counts["catalog.products"],
            "rows_by_table": counts,
            "import_order": IMPORT_ORDER,
            "csv_null_convention": "Nullable values are written as empty CSV fields.",
            "identity_strategy": (
                "Identity/FK columns are populated explicitly with deterministic positive 63-bit BIGINTs. "
                "The SQL schema uses GENERATED BY DEFAULT AS IDENTITY, so explicit IDs are valid."
            ),
            "price_note": (
                "template_v2 stores numeric prices without currency; listing_prices uses the --currency value "
                f"({currency} for this run)."
            ),
            "files": sorted(
                str(path.relative_to(temp_root).as_posix())
                for path in temp_root.rglob("*") if path.is_file()
            ),
        }
        write_json(temp_root / "_manifest" / "manifest.json", manifest)
        replace_output_tree(temp_root, output_dir)
        return manifest
    except Exception:
        if temp_root.exists():
            shutil.rmtree(temp_root, ignore_errors=True)
        raise


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Convert organised template_v2 mobile JSON into Supabase v3 CSV tables."
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=DEFAULT_INPUT_DIR,
        help=f"Organised JSON root (default: {DEFAULT_INPUT_DIR})",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=f"CSV output root (default: {DEFAULT_OUTPUT_DIR})",
    )
    parser.add_argument(
        "--site",
        action="append",
        default=[],
        help="Process only this source domain; repeat for multiple sites.",
    )
    parser.add_argument(
        "--canonical-source",
        default=DEFAULT_CANONICAL_SOURCE,
        help=f"Source used for specs.* canonical rows (default: {DEFAULT_CANONICAL_SOURCE})",
    )
    parser.add_argument(
        "--currency",
        default=DEFAULT_CURRENCY,
        help=f"Currency assigned to template_v2 numeric prices (default: {DEFAULT_CURRENCY})",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Stop on the first invalid input instead of writing it to metadata.etl_rejects.",
    )
    parser.add_argument(
        "--log-level",
        choices=("DEBUG", "INFO", "WARNING", "ERROR"),
        default="INFO",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    logging.basicConfig(
        level=getattr(logging, args.log_level),
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%H:%M:%S",
    )
    try:
        manifest = run_conversion(args)
    except Exception as exc:  # noqa: BLE001 - CLI boundary
        LOG.error("Conversion failed: %s", exc)
        if args.log_level == "DEBUG":
            LOG.exception("Detailed failure")
        return 1

    LOG.info(
        "CSV conversion complete: discovered=%d written=%d rejected=%d products=%d listings=%d output=%s",
        manifest["records_discovered"],
        manifest["records_written"],
        manifest["records_rejected"],
        manifest["products"],
        manifest["marketplace_listings"],
        manifest["output_directory"],
    )
    return 0 if manifest["records_rejected"] == 0 else 2


if __name__ == "__main__":
    sys.exit(main())
